### ISSUE TITLE
appstream.xml misses icon

### ISSUE THREAD

**Issue by damianatorrpm** [flathub/com.spotify.Client#112]
appstream.xml misses icon as icons are in this repo
I think they can be added just by one line each in the appstream?

**Comment by TingPing** [comment]
Check again once https://github.com/flathub/com.spotify.Client/commit/566f87f93e3f82fa73608777d4259d4c51decc0e is released

**Comment by damianatorrpm** [comment]
@TingPing I don't see an icon entry in the appdata.xml 
Is this being auto added?

**Comment by TingPing** [comment]
The appdata file references the desktop file, the desktop file references the icon name, the icons are then read.
