### ISSUE TITLE
get-scale-factor.py does not work in Plasma

### ISSUE THREAD

**Issue by hexchain** [flathub/com.spotify.Client#113]
The `get-scale-factor.py` script uses XSettings to find out the correct window scaling factor, but this method does not work in other DEs where XSettings isn't used, like Plasma.

I suggest falling back to the environment variable `GDK_SCALE` if XSettings is not available. This variable is set by Plasma 5.15+.

**Comment by Erick555** [comment]
`GDK_SCALE` isn't set for me on Plasma 5.17.4

**Comment by hexchain** [comment]
See https://github.com/KDE/plasma-workspace/blob/master/startkde/startplasma-x11.cpp#L70-L83 for the actual logic. For me, the value of that variable is 2, because I have a scale factor of 2.

AFAIK the Steam client currently also uses `GDK_SCALE`.

**Comment by Erick555** [comment]
I have scaling factor 1.5 and GDK_SCALE isn't set. Does it work only for integers?

**Comment by hexchain** [comment]
To be exact, it only sets that variable for scale factor greater than 2.

**Comment by TingPing** [comment]
Patch welcomed.

**Comment by hexchain** [comment]
#114 
Unfortunately, I didn't find a way to test the package with the change, due to the actual program being an `extra-data`.

**Comment by TingPing** [comment]
Thanks, seems straightforward enough.
