### ISSUE TITLE
Titlebar starts light and gets darker during startup

### ISSUE THREAD

**Issue by BjoernDaase** [flathub/com.spotify.Client#115]
Fedora 31

When starting Spotify the titlebar is in the light variant first, transitioning to the dark variant after a few seconds during startup.  
This does not really look good, instead it should be using the dark variant all the time.

**Comment by TingPing** [comment]
This is handled by #103

**Comment by JasonLG1979** [comment]
@TingPing you could always merge that already ;P

**Comment by TingPing** [comment]
I want to spend time learning how it works and I just don't have time. I also consider it an extremely minor bug so I'm not in a rush.

**Comment by JasonLG1979** [comment]
> I want to spend time learning how it works

It's really simple. Basically it uses a `while True` and a blocking x event handler to create a very simple event loop that when an x event happens it loops though all of the windows looking for Spotify. When it finds Spotify it uses subprocess to set the dark theme variant with xprops. If for some strange reason Spotify doesn't show up, like it crashed or whatever it will basically time out after a couple secs and just fallback to the equivalent of how you were doing it before.

Normally though everything happens and is done in less than a second (on my machine anyway). The variant is set before the window is mapped to the screen as far as I can tell so to a user the window never appears with a light window border.
