### ISSUE TITLE
Since recently spotify no longer plays audio

### ISSUE THREAD

**Issue by phw** [flathub/com.spotify.Client#116]
Spotify from Flathub unexpetedly stopped playing music. You can search, but when starting play back nothing happens.

Using latest updates from flathub with flatpak 1.6.0 on Arch Linux.

I can't tell what exactly is that changed, some update broke it. But I can't tell whether it has been flatpak itself, the runtime or the spotify package. But this issue at https://github.com/flathub/com.skype.Client/issues/89 , where the skype app also suddenly broke with some networking no longer working.

**Comment by TingPing** [comment]
Might be related to this also: https://github.com/flathub/com.discordapp.Discord/issues/73#issuecomment-578224416

Somebody tracked it down to a p11-kit update on Arch

**Comment by phw** [comment]
@TingPing Yes, that's right. Just found out about this as well, see

https://bugs.archlinux.org/task/65284?project=1&string=flatpak
https://github.com/flathub/com.valvesoftware.Steam/issues/526

Patches are being worked on for the runtime, see

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/2255
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/2249/diffs

Hope to see those released soon :) I'll close this one as this is unrelated to the app.
