### ISSUE TITLE
App opens up without title bar present

### ISSUE THREAD

**Issue by jonkoops** [flathub/com.spotify.Client#118]
Whenever I launch the app on my system (Fedora 31) the application starts without a title bar. It cannot be resized or moved around.

![Screenshot from 2020-01-28 15-11-46](https://user-images.githubusercontent.com/695720/73271275-91a1c800-41e0-11ea-8cd7-2e85e26ac640.png)

**Comment by TingPing** [comment]
Does it behave the same when doing `flatpak run --command=/app/extra/bin/spotify com.spotify.Client`?

**Comment by jonkoops** [comment]
Yes, it behaves the same with the following output to the console:

```
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
Gtk-Message: 15:34:59.152: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:34:59.152: Failed to load module "pk-gtk-module"
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[0128/153459.274665:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

```

**Comment by TingPing** [comment]
Well the bad news is its surely a Spotify bug and not package specific.

**Comment by jonkoops** [comment]
Well, that's a bummer. Nothing we can do here then.

**Comment by bumjrah** [comment]
Bump :(  Will a fix (temporary or otherwise) ever see the day of light here?

**Comment by sudopluto** [comment]
https://community.spotify.com/t5/Desktop-Windows/Spotify-open-in-full-screen-cannot-access-taskbar-anymore/td-p/1044311/page/3

was able to restore my titlebar by removing the window position settings in var/app/com.spotify.Client/config/spotify/prefs
