### ISSUE TITLE
"Something went wrong" when installing using gnome-software

### ISSUE THREAD

**Issue by robinst** [flathub/com.spotify.Client#12]
I get a generic "Something went wrong" error in Software when installing this package by clicking on Spotify here: https://flathub.org/apps.html

The following log is in `journalctl`:

> Nov 19 00:38:39 jon gnome-software[2105]: running install with refine-flags=require-origin with failure-flags=use-events,fatal-auth with timeout=60 on plugin=epiphany on apps system/flatpak/flathub/desktop/com.spotify.Client.desktop/stable took 125244ms
>
> Nov 19 00:38:39 jon gnome-software[2105]: **failed to call gs_plugin_refine_app on flatpak**: failed to get size: Ref runtime/org.gnome.Platform/x86_64/3.24 not installed
>
> Nov 19 00:38:39 jon gnome-software[2105]: running refine with refine-flags=require-license,require-url,require-size,require-version,require-history,require-setup-action,require-origin,require-menu-path,require-addons,require-provenance,require-icon,require-permissions,require-origin-hostname,require-runtime,require-screenshots with failure-flags=use-events with timeout=60 on apps system/flatpak/flathub/desktop/com.spotify.Client.desktop/stable took 1ms
>
> Nov 19 00:38:39 jon gnome-software[2105]: running refine with refine-flags=require-rating,require-reviews,require-review-ratings with failure-flags=use-events with timeout=60 on apps system/flatpak/flathub/desktop/com.spotify.Client.desktop/stable took 1ms

I was able to start the app though, and it seemed to work but then coredumped shortly after. I removed the app and tried installing again, and got the same error on installation. But the app seems to work better now.

I realize this might not be a very useful bug report, I'm sorry about that. (Also not sure this is the right place.)

This is on Fedora 27 with the following versions:

```
Name         : gnome-software
Version      : 3.26.2
Release      : 1.fc27
Arch         : x86_64

Name         : flatpak
Version      : 0.10.0
Release      : 1.fc27
Arch         : x86_64
```

**Comment by TingPing** [comment]
I don't think this would be the right place and the *gnome-software* product on https://bugzilla.gnome.org/ would be more relevant.

**Comment by robinst** [comment]
Thanks! Reported there now: https://bugzilla.gnome.org/show_bug.cgi?id=790751
