### ISSUE TITLE
No album cover in GNOME MPRIS player

### ISSUE THREAD

**Issue by BjoernDaase** [flathub/com.spotify.Client#121]
* Spotify 1.1.26.501.gbe11e53b (but also earlier versions)  
* Gnome 3.34.x and 3.35.x (and maybe earlier versions)

The GNOME MPRIS player (the one you get when you click on the date in the top bar) does not show album covers for songs played via Spotify. It is simply empty.  
Other apps (e.g. VLC) work fine.

**Comment by TingPing** [comment]
Can somebody report if it works in the `.deb` version on Ubuntu?

**Comment by fariasmarcos** [comment]
IIRC this has something to do with GNOME Shell capabilities, so it isn't related to Spotify itself. Try to run `sudo setcap -r /usr/bin/gnome-shell`, then restart the session.

**Comment by TingPing** [comment]
That sounds like a bad idea and I'm not sure it makes sense.

**Comment by BjoernDaase** [comment]
FWIW, the `Shortwave` flatpak also does not show album covers. So may be this is a flatpak issue?

**Comment by fariasmarcos** [comment]
It took me a while, but i finally found the issue i was referring to: https://gitlab.gnome.org/GNOME/gnome-shell/issues/2284

As i said, this is a gnome-shell issue. Doing the setcap thing is a workaround, however, it has implications, so you were right to be concerned about it.

**Comment by TingPing** [comment]
All the way down the rabbit hole its https://gitlab.gnome.org/GNOME/gvfs/issues/429

Anyway I'll just close this and mark it as an upstream bug.
