### ISSUE TITLE
Add workaround to get uri handling working

### ISSUE THREAD

**Issue by teohhanhui** [flathub/com.spotify.Client#123]
The current desktop file causes a new Spotify window to be opened when handling `spotify:` URIs (e.g. `xdg-open 'spotify:track:...'`), but it does not do what it's supposed to do, e.g. play a track or album etc.

I saw this: https://community.spotify.com/t5/Desktop-Linux/Guide-Play-Spotify-links-in-running-client/td-p/4647308 which uses dbus but it only works when an existing Spotify window is already open.

**Comment by ernstp** [comment]
Neat, it seems to work! Tested through Firefox.
