### ISSUE TITLE
How to disbable new track notification?

### ISSUE THREAD

**Issue by batisteo** [flathub/com.spotify.Client#125]
In Gnome, Spotify do not appear within the apps under Settings > Notifications > Applications.

Is there a settings to avoid getting a pop-up every 3 minutes?

**Comment by Erick555** [comment]
In spotify there is `Settings -> Display options -> Show desktop notifications when song changes`. Try unticking it.

**Comment by batisteo** [comment]
Oh gosh! How did I missed that?  
Thank you!
