### ISSUE TITLE
Spotify client sends notification even in DND mode

### ISSUE THREAD

**Issue by Latesil** [flathub/com.spotify.Client#135]
Silverblue 32, GNOME 3.36

Spotify client sends notifications even when DND mode is on. Or even when I explicitly forbid Spotify to send notification at all.

**Comment by ElXreno** [comment]
Fedora 32, KDE 5.18.5

I have a similar problem. When you disable notifications for an application, they still come, but in DND mode everything is fine.

**Comment by Erick555** [comment]
Does spotify behave differently when installed from somewhere else than flatpak?

**Comment by Latesil** [comment]
> Does spotify behave differently when installed from somewhere else than flatpak?

I can't check that because I use Silverblue and Flatpak in a single option for applications.

**Comment by TingPing** [comment]
This isn't a packaging issue and would need to be resolved somewhere else.
