### ISSUE TITLE
Error 451 while installing Spotify

### ISSUE THREAD

**Issue by Latesil** [flathub/com.spotify.Client#137]
Fedora 33, GNOME

Got this error while installing Spotify: 
```
Error: While downloading http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.1.26.501.gbe11e53b-15_amd64.deb: Server returned status 451: Unknown Error
error: Failed to install com.spotify.Client: While downloading http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.1.26.501.gbe11e53b-15_amd64.deb: Server returned status 451: Unknown Error
```

**Comment by HugLifeTiZ** [comment]
I just got this one myself. I also got it while trying to build the package whilst testing the spotifywm fix. I think this is a problem with upstream, which makes me wonder if we should really rely on upstream to reliably provide the data we need. Is flathub allowed to mirror the deb?

**Comment by Erick555** [comment]
> Is flathub allowed to mirror the deb?

No

**Comment by HugLifeTiZ** [comment]
Ah, drat. Bound by the whims of the Spotify debian repo server.
