### ISSUE TITLE
Flatpak install currently broken on Fedora

### ISSUE THREAD

**Issue by 00willo** [flathub/com.spotify.Client#143]
```
$ flatpak install flathub com.spotify.Client
Looking for matches…

com.spotify.Client permissions:
    ipc                     network        pulseaudio       x11       dri       file access [1]      dbus access [2]
    bus ownership [3]       tags [4]

    [1] xdg-music:ro, xdg-pictures:ro
    [2] org.freedesktop.Notifications, org.gnome.SessionManager, org.gnome.SettingsDaemon
    [3] org.mpris.MediaPlayer2.spotify
    [4] proprietary


        ID                          Branch         Op         Remote          Download
 1. [✗] com.spotify.Client          stable         i          flathub         1.0 kB / 138.2 MB

Error: While downloading http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.1.42.622.gbd112320-37_amd64.deb: Connection terminated unexpectedly
error: Failed to install com.spotify.Client: While downloading http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.1.42.622.gbd112320-37_amd64.deb: Connection terminated unexpectedly
```
Installed on Fedora32

**Comment by subpop** [comment]
This seems to be a deep-rooted CDN related issue by the upstream host[1]. I can't figure out if there's some workaround to force downloads to resume after being terminated or not.

1: https://community.spotify.com/t5/Desktop-Linux/Unable-to-Install-Spotify-Flatpak-package-on-Linux/td-p/5055661

**Comment by damluk** [comment]
See also https://github.com/flathub/com.spotify.Client/issues/108

**Comment by antonmos** [comment]
@TingPing  Why is this issue closed? Is there a resolution? This is still happening.

Thanks!

**Comment by TingPing** [comment]
There is nothing we can do about it. Spotify hosts their own data, we cannot rehost it, any errors that happen during downloads are out of our control. Sorry.

**Comment by FastOSlinux** [comment]
same error again:
1. [✗] com.spotify.Client     stable    i     flathub    106,8 MB / 138,2 MB

Erro: Enquanto baixava http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.1.42.622.gbd112320-37_amd64.deb: Connection terminated unexpectedly
erro: Falha ao instalar com.spotify.Client: Enquanto baixava http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.1.42.622.gbd112320-37_amd64.deb: Connection terminated unexpectedly

**Comment by jokeyrhyme** [comment]
My solution was to try it a few times every day until it worked :shrug: 

It might also help to use a VPN with an exit point in the USA

**Comment by antonmos** [comment]
> There is nothing we can do about it. Spotify hosts their own data, we cannot rehost it, any errors that happen during downloads are out of our control. Sorry.

thank you for the clarification!

For other who may be googling this:

**Comment by antonmos** [comment]
i was able to work around this by adding this to `/etc/hosts`
```
54.230.53.147 repository.spotify.com
```

per https://github.com/flathub/com.spotify.Client/issues/108#issuecomment-724978735
