### ISSUE TITLE
The client skips tracks during playback

### ISSUE THREAD

**Issue by Vladislavuz** [flathub/com.spotify.Client#144]
The client skips tracks during playback. Debian 8.

**Comment by TingPing** [comment]
No reason to believe this has anything to do with this specific package, unless you cannot reproduce on a different package of the same version.

**Comment by Vladislavuz** [comment]
> No reason to believe this has anything to do with this specific package, unless you cannot reproduce on a different package of the same version.

Deb version works fine.

**Comment by Erick555** [comment]
There are plenty of similar reports at [spotify forum](https://community.spotify.com/t5/Desktop-Linux/Spotify-continuously-skips-songs-on-linux/td-p/4776347). This isn't flatpak issue.
