### ISSUE TITLE
Old version - 1.1.46.916 is the latest version

### ISSUE THREAD

**Issue by vwbusguy** [flathub/com.spotify.Client#145]
The current version of the Linux spotify client appears to be 1.1.46 in the Snapstore and was released back in November: https://snapcraft.io/spotify
![image](https://user-images.githubusercontent.com/5474941/104060677-1c8a9100-51ac-11eb-989f-9aa872ffaf6a.png)

The current version on flathub is still on 1.1.42.622.

**Comment by Erick555** [comment]
Interesting, the latest deb still seems to be [1.1.42](https://repository-origin.spotify.com/pool/non-free/s/spotify-client/). Did they stopped releasing new linux versions outside snap?

**Comment by vwbusguy** [comment]
I'm out of my normal comfort zone here as a longtime Fedora user but I ran a container from ubuntu:latest and it appears that you are correct.  Following the Debian/Ubuntu instructions (after installing curl and gnupg and omitting sudo), I see:

```
root@a543fccab8d7:/# apt-cache show spotify-client
Package: spotify-client
Architecture: amd64
Version: 1:1.1.42.622.gbd112320-37
```

It looks like the snap is now their preferred delivery method and I have zero experience with snaps.

**Comment by vwbusguy** [comment]
Interestingly enough, it looks like the negativo repo has the latest version: https://negativo17.org/repos/spotify/fedora-33/x86_64/

**Comment by Erick555** [comment]
I wonder if they use snap as source. Anyway I made new version based on snap which you can test from [here](https://github.com/flathub/com.spotify.Client/pull/146#issuecomment-757249900).

**Comment by Erick555** [comment]
I wonder if they use snap as source. Anyway I made new version based on snap which you can test from https://github.com/flathub/com.spotify.Client/pull/146#issuecomment-757265861
