### ISSUE TITLE
GTK titlebar is no longer dark

### ISSUE THREAD

**Issue by connlim** [flathub/com.spotify.Client#158]
The GTK titlebar for Spotify on GNOME is no longer set to a dark theme. It now uses the default system theme (light theme in my case).

The issue seems to be in [this line of the python script used to set the dark titlebar](https://github.com/flathub/com.spotify.Client/blob/master/set-dark-theme-variant.py#L36). I found that it throws an exception: `[Errno 2] No such file or directory: 'xprop'`. It seems that the `xprop` tool was removed by the latest commit [65b7c91](https://github.com/flathub/com.spotify.Client/commit/65b7c917a29ea43c150ada9838adf6a0653e1cb4). Was this meant to be an intentional change? Thanks.

**Comment by lionirdeadman** [comment]
Yes, it was removed by mistake, I'm sorry. Thanks for catching that.

**Comment by 3ernhard** [comment]
The titlebar is light again since the last update. I think this happened, because the titlebar is empty (no title or text) now.

**Comment by alexmex90** [comment]
> The titlebar is light again since the last update. I think this happened, because the titlebar is empty (no title or text) now.

I am having the same issue, I'm running Fedora 34, it happens in both the Wayland session and xorg.
![Screenshot from 2021-10-17 00-26-30](https://user-images.githubusercontent.com/43529725/137616552-781f3829-5e2d-4c03-aa22-1de0208d9227.png)

When I close the app, the title gets displayed for a brief moment, before the window itself closes, but when running the app again, the title bar comes up empty again.
