### ISSUE TITLE
Titlebar theme not respecting system theme (adwaita dark instead of default)

### ISSUE THREAD

**Issue by alvilag** [flathub/com.spotify.Client#161]
Hello,

the window titlebar of the app is dark even if my theme is not--I'm using the Adwaita (default) theme on GNOME 3.38.4, Debian 11 Bullseye (running wayland).

Before the latest updates, or perhaps the very last (I'm now using 1.1.55.498.gf9a83c60), the app respected my theme and had the titlebar in light colors.

Is there a way to fix this? Although not the worst of the issues, the new appearance looks just off and inconsistent.

Thanks in any case for your work! Apart from this issue I really enjoy using the app.

Edit: I see there was a similar request to keep a light variant for the titlebar some time ago, [#50 ](https://github.com/flathub/com.spotify.Client/issues/50) (2018), and a dev said something about implementing an env var to control the titlebar theme. Was it implemented? If it is, how do I set it?

Thanks again.

**Comment by TingPing** [comment]
It was an accident that it returned to white: #159

No way to control it was ever added.

**Comment by alvilag** [comment]
Thanks for the quick reply!

Do you plan to add it? It would be nice to let the users choose.

**Comment by TingPing** [comment]
Sure. Once the new update is out you can do:

`flatpak override --user --env=SPOTIFYFLATPAK_DISABLE_DARK_TITLEBAR=1 com.spotify.Client`

**Comment by alvilag** [comment]
That's great, thanks a lot!

**Comment by juxuanu** [comment]
@TingPing Is there any way to set the titlebar to dark even tho I'm using Adwaita globally? I tried `GTK_THEME=Adwaita-dark` with no luck.

Could it be related to the fact that Spotify is not setting its window name anymore?
`xwininfo: Window id: 0x1000002 (has no name)`

**Comment by TingPing** [comment]
> Could it be related to the fact that Spotify is not setting its window name anymore?
xwininfo: Window id: 0x1000002 (has no name)

Yes thats exactly why. Maybe there is a different way of identifying the window and somebody can work around it but i haven't had time to look into it.
