### ISSUE TITLE
"Sorry, we're not able to play this video" - Problem with certain podcasts only (JRE)

### ISSUE THREAD

**Issue by false-9** [flathub/com.spotify.Client#163]
**Intro**

Hi, I'm having an issue with the client here. My setup is as follows:

- Elementary OS Hera 5.1.7
- Nvidia GTX 970 (Driver 470)
- i7 3770k
- 16GB DDR3

-------------------

- Dual-Monitor
- Headphones only
- Desktop PC

-------------------

- Spotify Account type: Free

**The Problem**

Having recently installed the Spotify client from flathub just to listen to some JRE podcasts, I thought I was having no problems while listening to/watching some of the most recent shows. However, when I try to listen to some earlier podcasts, I receive a blue pop-up message saying "Sorry, we're not able to play this video".

![1](https://user-images.githubusercontent.com/32708959/129749612-62fade2b-d4f2-4c82-9ce4-a9d405bc3f6f.png)

I've narrowed this down to from which show this problem starts to happen - The last good working podcast show from JRE seems to be '#1611 - Freddie Gibbs & Brian Moses' which was published on Feb 23. Any podcast before then seems to result in the error I'm describing. I should add though that I haven't tested every podcast before this point as this would take me forever, but from what I can see this seems to be the point where the problem introduces itself.

**Things I've tried**

- Reinstalling
- Deleting config files
- Enabling/Disabling Privacy from within the advanced settings (Block all third party cookies)
- VPN on / off, it doesn't matter - same result.

One thing to note is, when enabling privacy - block all third party cookies, the error doesn't happen right away, instead, the intro of the video plays for around 3 seconds before the error message appears, and the audio continues for around 7-8 seconds before halting, as opposed to having the privacy option disabled in which case the error message pops up right away after clicking play, with no video or audio at all.

**Comment by joshuag1000** [comment]
Is this still an issue with the latest version?
If is is broken please try using the test build from: #214

**Comment by kichirouhoshino** [comment]
> Is this still an issue with the latest version? If is is broken please try using the test build from: #214

I haven't tested video playback before, but it works for me.
![Screenshot from 2022-09-29 01-52-38-obfuscated](https://user-images.githubusercontent.com/78095397/192854233-eb07305f-6ea2-4e47-913c-45c5e6f8112a.png)

**Comment by joshuag1000** [comment]
> > Is this still an issue with the latest version? If is is broken please try using the test build from: #214
> 
> I haven't tested video playback before, but it works for me. ![Screenshot from 2022-09-29 01-52-38-obfuscated](https://user-images.githubusercontent.com/78095397/192854233-eb07305f-6ea2-4e47-913c-45c5e6f8112a.png)
> 
> I've also tested the mentioned podcast, and it played with no issues.

That's good.
I also tested it and it is working for me i just wanted op to check so they can close the issue if it is fixed.

**Comment by false-9** [comment]
Oh I don't know. I resorted to using the web client as this was a while ago. I'm not using the same setup anymore or distro. Good to know it seems to be working.

Cheers.
