### ISSUE TITLE
Tiling window managers no longer recognize spotify client

### ISSUE THREAD

**Issue by msdrigg** [flathub/com.spotify.Client#169]
Flathub spotify distribution uses spotifywm to set spotify's `WM_CLASS` property before launching the main window. This allows window managers to handle it properly.

Unfortunately, with the newest update to spotify, there is a [new issue](https://github.com/dasJ/spotifywm/issues/8) with spotifywm so spotify flatpak no longer works well with window managers. There haven't been any updates or workarounds that fix the issue up to this point. 

I don't know of any convenient work-around at this point.

**Comment by Erick555** [comment]
I think it's even worse in 1.1.67 where spotifywm can't find spotify window, see https://github.com/flathub/com.spotify.Client/pull/167#issuecomment-912040028

**Comment by ldelossa** [comment]
Currently experiencing this. Breaks swaywm's ability to identify Spotify.

**Comment by Erick555** [comment]
This is reported upstream: https://community.spotify.com/t5/Desktop-Linux/Few-broken-things-since-latest-update/td-p/5264045
