### ISSUE TITLE
The last build fails to apply extra data

### ISSUE THREAD

**Issue by fariasmarcos** [flathub/com.spotify.Client#176]
Since operations with extra-data aren't checked at build time, the build of #175 was successful, but the package fails to install.

**Version**: 1.1.68.632.g2b11de83
**Distro**: Fedora 34

**Comment by TingPing** [comment]
It did install here.. can you post logs?

**Comment by fariasmarcos** [comment]
Sure, the update command didn't say much. Also, my locale is pt_BR, so some of the messages are mixed with portuguese:

```
 Calling system helper: GetRevokefsFd
F: Calling system helper: GetRevokefsFd
F: flatpak_dir_pull: Using commit 3926923c6dd06e8e6b07c18609313a3fe6a33d3430702c3f41abf138b909ff0d for pull of ref app/com.spotify.Client/x86_64/stable from remote flathub

Atualizando…                        0%  0 byte/s
Atualizando… █                      5%F: Loading https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_53.snap using libsoup
Atualizando… ████████████████████ 100%  5,7 MB/s  00:00F: Received 169922560 bytes
F: Calling system helper: Deploy
Erro: Error deploying: Enquanto tentava aplicar dados extras: script apply_extra falhou, status de saída 256
Atualização concluída.                                                                           
erro: Houve um ou mais erros
```

**Comment by fariasmarcos** [comment]
Ah, I just tried to install the build directly from the PR, and it gave me some more useful information!

```
Filesystem uses lzo compression, this is unsupported by this version
Decompressors available:
	gzip
	xz
mv: cannot stat 'squashfs-root/usr/bin/spotify': No such file or directory
mv: cannot stat 'squashfs-root/usr/share/spotify': No such file or directory
rm: cannot remove 'squashfs-root': No such file or directory
```

**Comment by ma3yta** [comment]
```
Filesystem uses lzo compression, this is unsupported by this version
Decompressors available:
	gzip
	xz
mv: cannot stat 'squashfs-root/usr/bin/spotify': No such file or directory
mv: cannot stat 'squashfs-root/usr/share/spotify': No such file or directory
rm: cannot remove 'squashfs-root': No such file or directory
```

**Comment by nirfse** [comment]
I get the same update error on ArchLinux, failing with "Filesystem uses lzo compression, this is unsupported by this version".

**Comment by pratzyushd** [comment]
I get the same error running Pop!_OS 21.04 when trying to install Spotify. 

> ```
> Filesystem uses lzo compression, this is unsupported by this version
> Decompressors available:
> 	gzip
> 	xz
> mv: cannot stat 'squashfs-root/usr/bin/spotify': No such file or directory
> mv: cannot stat 'squashfs-root/usr/share/spotify': No such file or directory
> rm: cannot remove 'squashfs-root': No such file or directory
> ```

**Comment by stuarthayhurst** [comment]
I ran `flatpak install --user https://dl.flathub.org/build-repo/58231/com.spotify.Client.flatpakref` a couple days ago to test something, and that installed fine. It should be the same build, shouldn't it? What changed?

**Comment by pratzyushd** [comment]
@stuarthayhurst Just tried that command, and it has the same issue. I think it's something to do with Ubuntu recently updating the Snap to using LZO compression. Maybe the Flatpak is based on the Snap and so is breaking?

**Comment by stuarthayhurst** [comment]
Whoops, must've been an earlier test build I used then. Looks like it was in #174 
`flatpak install --user https://dl.flathub.org/build-repo/57908/com.spotify.Client.flatpakref` this one for for me when installing

**Comment by stuarthayhurst** [comment]
So is the repo just missing [these](https://github.com/flathub/com.spotify.Client/pull/174/commits/42bd26c810f324f5c4a2b95564b108c7f0f78d73) [commits](https://github.com/flathub/com.spotify.Client/pull/174/commits/714e3a7df62dd6dcfde211c329de1dd052396a2d)?

**Comment by pratzyushd** [comment]
> Whoops, must've been an earlier test build I used then. Looks like it was in #174
> `flatpak install --user https://dl.flathub.org/build-repo/57908/com.spotify.Client.flatpakref` this one for for me when installing

This worked for me surprisingly.

**Comment by stuarthayhurst** [comment]
Yep, that should be because that build has the 2 missing commits to handle the LZO stuff

**Comment by pratzyushd** [comment]
> So is the repo just missing [these](https://github.com/flathub/com.spotify.Client/pull/174/commits/42bd26c810f324f5c4a2b95564b108c7f0f78d73) [commits](https://github.com/flathub/com.spotify.Client/pull/174/commits/714e3a7df62dd6dcfde211c329de1dd052396a2d)? (2 different links)

Possibly, I'm not sure and I'm not too experienced with this stuff.

**Comment by pratzyushd** [comment]
> Yep, that should be because that build has the 2 missing commits to handle the LZO stuff

Ah brilliant, that explains it. Hopefully the dev resolves it soon
