### ISSUE TITLE
[1.1.68.632.g2b11de83] Wrong app size and no taskbar pinning

### ISSUE THREAD

**Issue by agurenko** [flathub/com.spotify.Client#180]
Since latest update, Spotify now opens at top left corner with some pre-determined size and does not remember new settings upon closing. That worked just fine before the last update. In addition the open window cannot be pinned to the task bar anymore on KDE Plasma 5.22.5 (both xorg and wayland session)

![Screenshot_20210922_122859](https://user-images.githubusercontent.com/6168150/134328499-c815e85d-90ac-47ee-a9ec-0bd34379e25e.png)

**Comment by Erick555** [comment]
This is upstream issue. As for now nobody came out with downstream solution. You may report it [here](https://community.spotify.com/t5/Desktop-Linux/bd-p/desktop_linux).

This is same problem as in https://github.com/flathub/com.spotify.Client/issues/179 and https://github.com/flathub/com.spotify.Client/issues/169

**Comment by agurenko** [comment]
Thanks, opened issue for everything there: https://community.spotify.com/t5/Desktop-Linux/Few-broken-things-since-latest-update/td-p/5264045

**Comment by HugLifeTiZ** [comment]
It's probably better to roll back to 1.1.55 for the time being. The newest release is *super* messed up. I posted instructions in that thread for rolling back to the last Flathub release before 1.1.68, but I think it might be worth considering for *Flathub* to roll back to 1.1.55 if possible. I know we have a policy of pushing out the latest stable releases, but I feel like that's predicated on trusting upstream to not push out broken crap. Spotify broke their end of the social contract.

**Comment by Erick555** [comment]
Does anyone knows for how long snap hosts old versions?

**Comment by Steve-Z** [comment]
Same window size and position behavior with Pop!_OS 20.04 and GNOME 3.36.8. This is the `~/.var/app/com.spotify.Client/config/spotify/prefs`
```
autologin.blob="..."
autologin.username="..."
app.window.position.saved=true
app.window.position.height=1005
app.autostart-mode="off"
app.window.position.y=75
autologin.canonical_username="..."
storage.last-location="/home/steve/.var/app/com.spotify.Client/cache/spotify/Storage"
app.window.position.width=1920
core.clock_delta=-1
app.last-launched-version="1.1.68.632.g2b11de83"
app.autostart-configured=true
```
My reading of this file sees the height and width as being properly configured as well as the value "true" to save the window position. It seems the app is just ignoring this?
