### ISSUE TITLE
Title bar coming up empty

### ISSUE THREAD

**Issue by alexmex90** [flathub/com.spotify.Client#184]
I have installed the app from flatpak in Fedora 34, title bar is coming up without text.

![image](https://user-images.githubusercontent.com/43529725/137643825-d07e6825-3a50-4fef-b7e7-d7f888a6a024.png)

Let me know if you need me to do some sort of debugging.

**Comment by alexmex90** [comment]
#158 https://github.com/flathub/com.spotify.Client/issues/158

**Comment by ahayzen** [comment]
Note that the nixpkg of Spotify, which is also made from the snap, works correctly and is using version 1.1.68.632.g2b11de83

Not sure if their definition gives any clues what could be different or what they changed in the history of the file to fix it https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/spotify/default.nix

**Comment by Erick555** [comment]
Some distros decided to make [spotify-specific](https://github.com/pop-os/shell/pull/1174) patches for their DE.

**Comment by rafifos** [comment]
@Erick555 even with these patches, it's still broken.
See https://github.com/pop-os/shell/issues/740#issuecomment-961957384

**Comment by msdrigg** [comment]
It works with the standard deb install and the snap install. There is something in the flatpak install that breaks it

**Comment by kerossin** [comment]
Are other packages also using [spotifywm](https://github.com/dasJ/spotifywm)?

The Nix package doesn't seem to have it as a dependency so maybe spotifywm could be the culprit since it does try to set the class name?

**Comment by Erick555** [comment]
removing reference to spotifywfm didn't help for me. You may try yourself by editing [launcher](https://github.com/flathub/com.spotify.Client/blob/master/spotify-bin#L40) in your installation.

**Comment by msdrigg** [comment]
Via trial and error, I have found that spotify removes the `icons` folder from the spotify deb. If the icons folder is restored to the `files/extra/share/spotify` directory, then it works again. I'll figure out a pr in a sec
