### ISSUE TITLE
Blank screen on Fedora 35 running on nouveau driver

### ISSUE THREAD

**Issue by ocosta** [flathub/com.spotify.Client#187]
Spotify was running just fine on Fedora 34, but this is not the case anymore with Fedor 35. All I see is a blank screen. If I run it from the console I get this:

```
flatpak run com.spotify.Client 
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
[spotifywm] attached to spotify
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify
Gtk-Message: 22:57:33.052: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:57:33.052: Failed to load module "pk-gtk-module"
Gtk-Message: 22:57:33.052: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:57:33.052: Failed to load module "pk-gtk-module"
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[spotifywm] attached to spotify
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

**Comment by TingPing** [comment]
These aren't really actionable issues. Spotify, and Bitwarden, use Chromium which has expectations about OpenGL working.

So I would say your issues are entirely between Chromium <-> Nouveau. And some changes will need to happen there.

**Comment by ocosta** [comment]
Thanks for the info, I guess that makes sense. I would happily file this upstream, but I'm afraid I probably won't be able to provide much info for them, unless there is any specific tests I could do. Any tips? Otherwise, I guess I'll just have to wait indeed...

**Comment by TingPing** [comment]
Yeah, unless you are very familiar with Chromium it would be very hard to track down.

**Comment by hiredman** [comment]
I get a blank screen on fedora rawhide on intel

**Comment by ocosta** [comment]
Mmmh... so it's not exclusive to nouveau. Maybe this will attract more attention from Chromium devs?

**Comment by hiredman** [comment]
Sorry for the noise, I thought I deleted my comment. When I left Spotify
open long enough(enough to find this issue and leave a comment) eventually
the ui rendered, and everything seems fine now.

**Comment by ocosta** [comment]
Thanks for the clarification. Well, I got some news as well: installed nvidia's proprietary driver (from Negativo17.org), and now both Spotify and Bitwarden are working again, with no delays -- but Telegram crashes right from the start, claiming "Open GL issues". It automatically disabled "OpenGL rendering for media" setting. So, it does seem to be related to nouveau somehow. But the Telegram issue was sort of a plot-twist...

**Comment by Zlopez** [comment]
As Fedora 35 is no longer even supported by Fedora is this still relevant?
