### ISSUE TITLE
Doesnt start on Kubuntu, no Wayland support

### ISSUE THREAD

**Issue by firefoxlover** [flathub/com.spotify.Client#193]
**EDIT: It works now, in Flatseal I had to allow X11-Windows and Fallback to X11-Server. Spotify seems to not have an implementation for Wayland yet.**

The .desktop file doesnt work. When executing the open command in terminal, I get:

`user@laptop:~$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=spotify --file-forwarding com.spotify.Client @@u %U @@`
`user@laptop:~$ /app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)`
`[spotifywm] attached to spotify`
`/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)`
`/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)`
`[spotifywm] attached to spotify`
`Traceback (most recent call last):`
`  File "/app/bin/set-dark-theme-variant.py", line 11, in <module>`
 `   disp = Xlib.display.Display()`
  `File "/app/lib/python3.9/site-packages/Xlib/display.py", line 89, in __init__`
`    self.display = _BaseDisplay(display)`
`  File "/app/lib/python3.9/site-packages/Xlib/display.py", line 71, in __init__`
  `  protocol_display.Display.__init__(self, *args, **keys)`
`  File "/app/lib/python3.9/site-packages/Xlib/protocol/display.py", line 84, in __init__`
    `name, protocol, host, displayno, screenno = connect.get_display(display)`
`  File "/app/lib/python3.9/site-packages/Xlib/support/connect.py", line 73, in get_display`
`    return mod.get_display(display)`
`  File "/app/lib/python3.9/site-packages/Xlib/support/unix_connect.py", line 76, in get_display`
    `raise error.DisplayNameError(display)`
`Xlib.error.DisplayNameError: Bad display name ""`
`[spotifywm] attached to spotify`

`(spotify --force-device-scale-factor=1 %U:6): Gtk-WARNING **: 13:45:37.808: cannot open display:`

**Comment by Erick555** [comment]
Does `flatpak run --command=/app/extra/bin/spotify com.spotify.Client` work?

**Comment by firefoxlover** [comment]
> Does `flatpak run --command=/app/extra/bin/spotify com.spotify.Client` work?

user@laptop:~$ flatpak run --command=/app/extra/bin/spotify com.spotify.Client
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)

(spotify:2): Gtk-WARNING **: 16:45:48.588: cannot open display:

**Comment by TingPing** [comment]
> EDIT: It works now, in Flatseal I had to allow X11-Windows and Fallback to X11-Server. Spotify seems to not have an implementation for Wayland yet.

This application never had the permission that disabled X11, so maybe you configured that by accident globally or something.

**Comment by visor841** [comment]
For me on Kubuntu, Spotify will only start if I specifically *disable* Wayland permission in flatseal, even if I have X11 fallback enabled. Seems like the fallback isn't working if Wayland access is granted.

**Comment by Kakoks** [comment]
Can confirm, doesn't work on wayland, only on X11

**Comment by TingPing** [comment]
This application has always required X11 and XWayland.

The OP even corrected that they changed permissions which caused the issue.
