### ISSUE TITLE
Audio will not play on ubuntu 21.10 gnome

### ISSUE THREAD

**Issue by Dangerdonny** [flathub/com.spotify.Client#196]
On gnome 21.10, the audio just wont play at all. I've tried messing around with pulse effects but that did nothing.

**Comment by nicokimmel** [comment]
Can confirm this. Im under Arch, Gnome 42.1.
I swapped `wireplumber` with `pipewire-media-session` and its working again.

**Comment by alvarlagerlof** [comment]
This just started happening recently for me too. It has worked under `wireplumber` for quite a while before this started for me.

**Comment by alvarlagerlof** [comment]
Why is it completed?

**Comment by alvarlagerlof** [comment]
Why is it completed?
