### ISSUE TITLE
Can't update - invalid exec argument

### ISSUE THREAD

**Issue by did-not-read-it** [flathub/com.spotify.Client#200]
When I try to update via the terminal, I run into the following error:
`Error: invalid Exec argument @@u`

Is there something that is interfering with the app to update? I'm on Zorin OS 16.1.

**Comment by TingPing** [comment]
I can't reproduce, it could be a flatpak bug, which version of `flatpak` do you have? And can you try the latest version if its not.

**Comment by Erick555** [comment]
I can't reproduce either. I think revert was premature here.

**Comment by JasonLG1979** [comment]
If this was the reason for the revert it also should be noted that 1.1.84.716 actually contains what appears to be a fully functioning MPRIS implementation which is a pretty big milestone for me anyway.

**Comment by brxken128** [comment]
I also cannot reproduce the issue, it seems to be unique to @did-not-read-it

**Comment by JasonLG1979** [comment]
Zorin OS 16.1 is based on Ubuntu 20.04 and at this point it's flatpak version is a little long in the tooth if they're using the same version as upstream Ubuntu.

I'm currently on Ubuntu 22.04 and had no problem at all with 1.1.84.716.
