### ISSUE TITLE
No Media controls in Taskbar Preview in Spotify for kde

### ISSUE THREAD

**Issue by pakosaan** [flathub/com.spotify.Client#208]
It works Perfectly with the Aur Packages but not with the flatpak version.

**Comment by Erick555** [comment]
Do you mean something else than _Media Player_ applet? That one works for me.

**Comment by TingPing** [comment]
Works in GNOME also. The package has rights to `org.mpris.MediaPlayer2.spotify` I wouldn't expect any difference between the host package.

**Comment by TingPing** [comment]
KDE tries to associate the window with the mpris instance and fails.

Duplicate of #58
