### ISSUE TITLE
404

### ISSUE THREAD

**Issue by kumiokru** [flathub/com.spotify.Client#21]
flatpak install flathub com.spotify.Client

error: While downloading https://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.64.407.g9bd02c2d-26_amd64.deb: Server returned status 404: Not Found

So spotify just updated the package.

**Comment by ace13** [comment]
Spotify seem to have started supplying a snap instead of deb packages.

**Comment by Lonsfor** [comment]
The deb files are still there, they just pushed an update.

**Comment by Lonsfor** [comment]
https://community.spotify.com/t5/forums/v3_1/forumtopicpage/board-id/desktop_linux/page/14/thread-id/1

> Spotify 1.0.69 in the testing repository now (soon stable) **can dynamically load different versions of libcrypto.so (from the libssl* packages).**

👀

**Comment by Barthalion** [comment]
@ace13 Hard to say whether it's official, and seeing that Canonical's press release doesn't mention Spotify involvement, I realy doubt it.

@Lonsfor: Can you test it? Merged pull request by @kumiokru for now.

**Comment by Lonsfor** [comment]
Ok i tried testing it, it was the first time i actually build-ed a flatpak but by following [this](https://flatpak.org/hello-world) i think i did it.   

It did seemed to work, local files still don't work but its been like than for awhile now.

if there isn't anything else to look at i can make the PR
