### ISSUE TITLE
glitches while playing music on Fedora 36

### ISSUE THREAD

**Issue by pedromellofh** [flathub/com.spotify.Client#210]
sound fails like there is a high cpu usage, but there isn't. the web player works like a charm. audio quality is set to automatic.

**Comment by TingPing** [comment]
Unless you have evidence this works outside of flatpak nothing here is actionable.

**Comment by pedromellofh** [comment]
the same not occurs when installed via snap

**Comment by pedromellofh** [comment]
forget about it. detected the same issue on snap too, although in a lesser extent. closing the issue here.
