### ISSUE TITLE
App doesn't minimize to system tray 

### ISSUE THREAD

**Issue by ZiadEl-kashif** [flathub/com.spotify.Client#211]
OS - Kubuntu 22.04 
KDE - 5.25.5
Windowing system - Wayland
Kernel - 5.15.0-47
App Version - 1.1.84.716.gc5f8b819
------------------------------------------------------------
**Problem**: 
I have the "close button should minimize the spotify Window" on
And yat it closes the application entirely 

Bs. This is my first time failing a report EVER so if there is any mor information i can provide please let me know.

**Comment by rowbawts** [comment]
**OS - Fedora 36 Silverblue
GNOME - 42
Windowing System - Wayland
Kernel - 5.19.13-200.fc36.x86_64
App Version - 1.1.84.716.gc5f8b819**

Same issue here.

**Comment by upfringe** [comment]
I think minize to tray wont be fixed . it has been the issue from many years before and it is not fixed till the date so i think it wont be fixed in the future also.
Spotify in linux uses the half GB of ram so for  me it is unusable as i dont have excess ram just to play spotify. Playing in the web  version is better option than running spotify desktop client.

**Comment by TingPing** [comment]
Are you saying it supports this feature in other packages?

I tried adding libappindicator to the package and it didn't change anything.

**Comment by ZiadEl-kashif** [comment]
> Are you saying it supports this feature in other packages?
> 
> I tried adding libappindicator to the package and it didn't change anything.

All I'm saying is that i tried the deb and it was working and i have a friend on the same system as mine with the only difference is that he uses Ubuntu Gnome and its also working with him fine

**Comment by Erick555** [comment]
Do you mean spotify uses tray or is just minimized? Those aren't the same thing.

BTW: in session bus log I see:
```
C21: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
Filtering message due to arg0 org.gnome.SettingsDaemon.MediaKeys, policy: 0 (required 2)
*HIDDEN* (ping)
B-1: <- org.freedesktop.DBus return from C21
*REWRITTEN*
C22: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
Filtering message due to arg0 org.gnome.SettingsDaemon.MediaKeys, policy: 0 (required 1)
B-1: <- org.freedesktop.DBus return from C22
*REWRITTEN*
C23: -> org.gnome.SettingsDaemon.MediaKeys call org.gnome.SettingsDaemon.MediaKeys.GrabMediaPlayerKeys at /org/gnome/SettingsDaemon/MediaKeys
```

Dos it mean `--talk-name=org.gnome.SettingsDaemon` should be changed to `--talk-name=org.gnome.SettingsDaemon.MediaKeys`?

**Comment by ZiadEl-kashif** [comment]
> Do you mean spotify uses tray or is just minimized? Those aren't the same thing.
> 
> BTW: in session bus log I see:
> ```
> C21: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
> Filtering message due to arg0 org.gnome.SettingsDaemon.MediaKeys, policy: 0 (required 2)
> *HIDDEN* (ping)
> B-1: <- org.freedesktop.DBus return from C21
> *REWRITTEN*
> C22: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
> Filtering message due to arg0 org.gnome.SettingsDaemon.MediaKeys, policy: 0 (required 1)
> B-1: <- org.freedesktop.DBus return from C22
> *REWRITTEN*
> C23: -> org.gnome.SettingsDaemon.MediaKeys call org.gnome.SettingsDaemon.MediaKeys.GrabMediaPlayerKeys at /org/gnome/SettingsDaemon/MediaKeys
> ```
> 
> Dos it mean `--talk-name=org.gnome.SettingsDaemon` should be changed to `--talk-name=org.gnome.SettingsDaemon.MediaKeys`?

I don't understand most of this technical stuff 
But as for your question it suppose to be like
1.the option is checked in spotify settings 
2.When heating the close button on spotify Window it's suppose to close the window and keep the app running in the background with a spotify icon indicator in the system tray

**Comment by joshuag1000** [comment]
I'm thinking this may be an upstream issue.
I ran the application locally without using flatpak and the icon didnt work and there were no visible errors.

> Dos it mean --talk-name=org.gnome.SettingsDaemon should be changed to --talk-name=org.gnome.SettingsDaemon.MediaKeys?

I dont think this would actually change anything as i believe `--talk-name=org.gnome.SettingsDaemon` gives access to `--talk-name=org.gnome.SettingsDaemon.MediaKeys`

**Comment by TingPing** [comment]
> I dont think this would actually change anything as i believe --talk-name=org.gnome.SettingsDaemon gives access to --talk-name=org.gnome.SettingsDaemon.MediaKeys

It does not actually. I've updated this permission but it is unrelated to this issue.

**Comment by joshuag1000** [comment]
> > I dont think this would actually change anything as i believe --talk-name=org.gnome.SettingsDaemon gives access to --talk-name=org.gnome.SettingsDaemon.MediaKeys
> 
> It does not actually. I've updated this permission but it is unrelated to this issue.

you learn something everyday.

**Comment by rpolnx** [comment]
Any news?

**Comment by TingPing** [comment]
I tested both the native Ubuntu package and the Snap on Ubuntu 22.04. I genuinely think Spotify just doesn't support a tray, exposes a broken setting, and is all around not very tested on Linux.

So I'm just going to close this. Bring up the issue with upstream.

**Comment by famiu** [comment]
This seems to be fixed for me now, wonder if it's just me or if it's fixed in general.

**Comment by joshuag1000** [comment]
> This seems to be fixed for me now, wonder if it's just me or if it's fixed in general.

This was fixed by some recent patches:
See: https://github.com/flathub/com.spotify.Client/pull/261 and https://github.com/flathub/com.spotify.Client/commit/65d48cf5fc64dd4527622fd2d65890e10b7b6223
