### ISSUE TITLE
Local files wouldn't play anymore

### ISSUE THREAD

**Issue by kichirouhoshino** [flathub/com.spotify.Client#213]
After updating to the newest version (the update from runtime 21.08 to 22.08), I couldn't play local files anymore.

![Screenshot from 2022-09-28 11-47-36](https://user-images.githubusercontent.com/78095397/192683109-d32a7409-f21b-4511-8a4c-a6de8cdd1389.png)

**Comment by Erick555** [comment]
Spotify needs ffmpeg 4.4 while new runtime has 5.x

**Comment by joshuag1000** [comment]
> Spotify needs ffmpeg 4.4 while new runtime has 5.x

yeah after seeing this issue i realised that. im working on adding 4.4 into the app.

**Comment by joshuag1000** [comment]
@kichirouhoshino I have created a pr. when the buildbot builds a test would you mind just installing it to check that the fix also works for you?

**Comment by kichirouhoshino** [comment]
> @kichirouhoshino I have created a pr. when the buildbot builds a test would you mind just installing it to check that the fix also works for you?

It works now :+1:

**Comment by joshuag1000** [comment]
Great to hear.
Just need to wait for it to be merged.
