### ISSUE TITLE
Spotify window flashing black

### ISSUE THREAD

**Issue by Razer0123** [flathub/com.spotify.Client#217]
On Wayland Spotify window flashes black then goes back to normal (i'm using Pop Shell for tiling)

This is what running it via terminal shows

```
[alessandro@fedora ~]$ flatpak run com.spotify.Client
[alessandro@fedora ~]$ /app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
[spotifywm] attached to spotify
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify
Gtk-Message: 20:19:10.910: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:19:10.910: Failed to load module "pk-gtk-module"
Gtk-Message: 20:19:10.910: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:19:10.910: Failed to load module "pk-gtk-module"
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[spotifywm] spotify window found
[spotifywm] attached to spotify
[alessandro@fedora ~]$ [spotifywm] spotify window found
[spotifywm] spotify window found
[spotifywm] spotify window found

```

**Comment by TingPing** [comment]
Do you have any reason to believe this has something to do with this package?

Chrome+Xwayland just is a bad combination  IME.

**Comment by Razer0123** [comment]
> Do you have any reason to believe this has something to do with this package?
> 
> Chromium+Xwayland just is a bad combination IME.

I don't. I just thought I had to post it here since it was happening on Spotify, it's the only app having this issue

**Comment by sindre0830** [comment]
Happens for me as well after latest update

**Comment by joshuag1000** [comment]
> It happens for me as well after the latest update.
> 
> EDIT:
> 
> Downgrading the package to a previous version didn't fix it. It probably has something to do with Fedora.

What version of the kernel are you using?
What desktop environment and version?
X11 or wayland?

**Comment by sindre0830** [comment]
> What version of the kernel are you using?

5.19.14-200.fc36.x86_64
> What desktop environment and version?

Fedora Linux 36 (Workstation Edition)
> X11 or wayland?

Wayland

**Comment by sindre0830** [comment]
> > > > It happens for me as well after the latest update.
> > > > EDIT:
> > > > Downgrading the package to a previous version didn't fix it. It probably has something to do with Fedora.
> > > 
> > > 
> > > What version of the kernel are you using?
> > > What desktop environment and version?
> > > X11 or wayland?
> > 
> > 
> > 5.19.14-200.fc36.x86_64
> > Fedora Linux 36 (Workstation Edition)
> > Wayland
> 
> Out of curiosity have you tried to see if this still happens in x11?

Switching to X11 seems to fix it.

**Comment by joshuag1000** [comment]
> > > > > It happens for me as well after the latest update.
> > > > > EDIT:
> > > > > Downgrading the package to a previous version didn't fix it. It probably has something to do with Fedora.
> > > > 
> > > > 
> > > > What version of the kernel are you using?
> > > > What desktop environment and version?
> > > > X11 or wayland?
> > > 
> > > 
> > > 5.19.14-200.fc36.x86_64
> > > Fedora Linux 36 (Workstation Edition)
> > > Wayland
> > 
> > 
> > Out of curiosity have you tried to see if this still happens in x11?
> 
> Switching to X11 seems to fix it.

Like mentioned before then there is a chance that this is an xwayland issue / spotify  and maybe not an issue with flatpak but im not 100% sure and i could be wrong

**Comment by Razer0123** [comment]
Seems to be an issue related to Nvidia and Flatpaks

I've read of people having the same issue with VScode

**Comment by TingPing** [comment]
I'm closing this as we can't fix actual Spotify bugs.

**Comment by uncomfyhalomacro** [comment]
For anyone that comes across this issue, you just have to disable GPU Acceleration. I did this with Flatseal 
![image](https://github.com/flathub/com.spotify.Client/assets/66054069/f7bd0836-5e49-42aa-ad27-bd24452d602e)
