### ISSUE TITLE
Spotify will not open, missing libcurl-gnutls.so.4

### ISSUE THREAD

**Issue by mpanhans** [flathub/com.spotify.Client#229]
The Spotify flatpak worked fine for me in the past, but after a few months of not opening it, I find now I cannot launch it.
flatpak run com.spotify.Client returns:
/app/extra/bin/spotify: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

I supposed I messed something up, but uninstalling and re-installing the Spotify client from flathub still gives me the same issue. Any ideas on how I can fix this?

**Comment by TingPing** [comment]
Works here.

The library is very much there: `flatpak run --command=ls com.spotify.Client /app/lib`

**Comment by mpanhans** [comment]
Thanks. I just ran `flatpak run --command=ls com.spotify.Client /app/lib` and I do see libcurl-gnutls.so.4 listed. I'm not sure how I managed to break launching Spotify.

**Comment by mpanhans** [comment]
I guess perhaps my question should be, when I launch com.spotify.Client, why does it search for the library in /app/extra/bin/spotify ? And can/should I tell it that it should search in /app/lib instead?

**Comment by TingPing** [comment]
Flatpak configures this all by default:

`flatpak run --devel --command=ldconfig com.spotify.Client --verbose`

However I do see something fishy:

> ```
> libcurl.so.4 -> libcurl-gnutls.so.4ldconfig: Can't link /app/lib/libcurl.so.4 to libcurl-gnutls.so.4
>  (SKIPPED)
> ```

**Comment by TingPing** [comment]
@mpanhans This is a total guess but once the bot builds this can you install it to test: https://github.com/flathub/com.spotify.Client/pull/230

**Comment by mpanhans** [comment]
Yes this test build works fine on my system! When launching it from the terminal, I do get some messages, see below. But yes launching the app now works like I would expect it to.

```
[spotifywm] attached to spotify
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify
Gtk-Message: 22:14:13.799: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:14:13.800: Failed to load module "canberra-gtk-module"
/proc/self/exe: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /proc/self/exe)
[spotifywm] attached to spotify
[spotifywm] spotify window found
```
