### ISSUE TITLE
Cannot login in Spotify

### ISSUE THREAD

**Issue by jcruzs** [flathub/com.spotify.Client#240]
Os: Opensuse Tumbleweed
       Gnome 44
       Intel

Opening spotify from flathub the login is thorugh the web browser. However, the browser will open and I login and the next message appear in the window

response_type parameter is missing

And no way to login in spotify

Regards,

**Comment by Victor239** [comment]
Delete the contents of `/home/USER/.var/app/com.spotify.Client/` then try to log in again. I think I was logged out due to being in another country than my account, as when I tried to log back in an error showed until I switched on a VPN.

**Comment by dxomg** [comment]
Hello, It would be very nice if this could get fixed

**Comment by TingPing** [comment]
Any issue like this is a Spotify bug.
