### ISSUE TITLE
com.spotify.Client won't update or install in flatpak cli

### ISSUE THREAD

**Issue by aaron-watts** [flathub/com.spotify.Client#244]
Following error message when running `flatpak update com.spotify.Client`:

`Error: While downloading https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_67.snap: Server returned status 503: Service Unavailable`

Following error message when running `flatpak install com.spotify.Client` after uninstall:

```
Error: While downloading https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_67.snap: Server returned status 503: Service Unavailable
error: Failed to install com.spotify.Client: While downloading https://api.snapcraft.io/api/v1/snaps/download/pOBIoZ2LrCB3rDohMxoYGnbN14EHOgD7_67.snap: Server returned status 503: Service Unavailable
```

**Comment by Erick555** [comment]
It work for me. Maybe temporary server issues, try again later.
