### ISSUE TITLE
version 1.2.11.916.geb595a67 outdated

### ISSUE THREAD

**Issue by kolAflash** [flathub/com.spotify.Client#248]
Current Flathub version: `1.2.11.916.geb595a67` (19 May 2023)

https://snapcraft.io/spotify  
latest/stable: `1.2.13.661.ga588f749` (8 September 2023)  
latest/edge: `1.2.20.1210.g2a8a8a57` (8 September 2023)

http://repository.spotify.com (DEB): `1.2.18.999.g9b38fc27` (14 August 2023)

Unfortunately I can't say if these versions fix critical (security related) bugs, because Spotify provides no changelog.

**Comment by Erick555** [comment]
https://github.com/flathub/com.spotify.Client/pull/247

**Comment by YuriBrandi** [comment]
I think a beta flatpak branch version with automerging would be highly appreciated by those who always want to be up to date.

Stable -> manual merging
Beta -> automerging.

Maybe even consider the Snap edge as upstream for the Beta branch.

**Comment by Erick555** [comment]
Bot updates work only for single branch so if beta get autoupdates then stable wouldn't ave any updates at all.

**Comment by YuriBrandi** [comment]
Uh so if we create a beta branch in the same project, fluthubbot won't work for both branches, right? : /

I tried to push a separate Flatpak for Spotify Edge w/ automerging a couple of weeks ago, but Flathub's contributors didn't really like the idea of a duplicate app (which exists for many apps like Discord btw).

**Comment by bbhtt** [comment]
> Uh so if we create a beta branch in the same project, fluthubbot won't work for both branches, right? : /

No

You can use a custom Github workflow for that. Lots of browsers on Flathub do.

**Comment by Erick555** [comment]
This can be closed.

**Comment by kolAflash** [comment]
Thanks :-)
