### ISSUE TITLE
Determine spotify stable version from repo info

### ISSUE THREAD

**Issue by ahayzen** [flathub/com.spotify.Client#25]
Is it possible to determine the stable version from the repository information? (This comes from comments I saw on a previous pull request [0])

So the two debs we are interested in come from the `pool` folder [1], as of the time of writing the stable version is `spotify-client_1.0.69.336.g7edcc575-39_amd64.deb` or `spotify-client_1.0.69.336.g7edcc575-39_i386.deb`. 

Now if you look in the `dists` folder there are two files [2] (amd64) [3] (i386) which have a load of information in them, in particular a line `Filename: pool/non-free/s/spotify-client/spotify-client_1.0.69.336.g7edcc575-39_amd64.deb` or `Filename: pool/non-free/s/spotify-client/spotify-client_1.0.69.336.g7edcc575-39_i386.deb` grouped in the section for `Package: spotify-client` which matches the stable debs above.

It was asked in the pull request [0] if the version could be extracted from the repository but no information was provided, so I wondered with this new information whether a script would be able to determine the url ?

0 - https://github.com/flathub/com.spotify.Client/pull/18
1 - https://repository-origin.spotify.com/pool/non-free/s/spotify-client/
2 - https://repository-origin.spotify.com/dists/stable/non-free/binary-amd64/Packages
3 - https://repository-origin.spotify.com/dists/stable/non-free/binary-i386/Packages

**Comment by ahayzen** [comment]
Also noticed there are `SHA256` and `Size` fields in [2] and [3] that match what has been put in the flatpak `extra-data`definition.

**Comment by Barthalion** [comment]
Using it would mean that we no longer rely on flatpak to verify checksums of extra-data (or we need a way to dynamically pass these somehow). In general sounds good, and can be completely implemented in apply_extra script.

**Comment by ahayzen** [comment]
Right, and I also fear that Spotify may not release any new deb's now that they are using Snap's for distribution :-/ They do state "From now on, the snap package will be preferred, that we will guide users toward, but the debian package will still be available for now." [4], so hopefully they will but just something to watch out for. (see below for comparison of versions in deb vs snap repos)

From what I can see there are only two apps in flathub which would require this script, Spotify and Skype. So I wonder if it is worth writing such a script or not ?

For reference these are the versions of the client in the deb and snap repos, it looks like the snap versions are one in front of the debs.
Deb versions [1]
stable  1.0.69.336.g7edcc575-39
testing 1.0.70.399.g5ffabd56-26

Snap versions [5]
stable       1.0.70.399.g5ffabd56-26
candidate 1.0.72.117.g6bd7cc73-35

4 - https://community.spotify.com/t5/Desktop-Linux/Spotify-now-has-a-Snap-package-as-well/m-p/4221993/highlight/true#M14165
5 - https://pastebin.ubuntu.com/26427160/

**Comment by Barthalion** [comment]
Also another problem I see is that such script would have to check for upgrades on start, as it wouldn't be tracked in the repository itself, which probably isn't possible after extra-data is applied.

**Comment by ahayzen** [comment]
FWIW, the flatpak external data checker tool [6] basically does this task, it has been suggested this could run on the flathub servers at a regular interval.

6 - https://github.com/joaquimrocha/flatpak-external-data-checker/
