### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Victor239** [flathub/com.spotify.Client#256]
Changelogs can be displayed on Flathub and within distro app updaters, all that's needed is an `.appdata`/[.metainfo.xml](https://docs.flatpak.org/en/latest/conventions.html#appdata-files) file. 

See these examples of another app's [appdata.xml](https://github.com/flathub/io.github.trigg.discover_overlay/blob/master/io.github.trigg.discover_overlay.appdata.xml), and how their changelog is [displayed on Flathub](https://flathub.org/en-GB/apps/io.github.trigg.discover_overlay).

**Comment by Erick555** [comment]
AFAIK spotify doesn't publish changelogs. Please don't mass-open issues in every repo.

**Comment by Victor239** [comment]
Apologies but I got quite frustrated seeing that there aren't changelogs available for most apps, unlike other app stores or installation methods. 

If the packager is unable to publish a changelog that's fine, but I searched issues on these repos first and no-one had brought it to the packager's attention before.
