### ISSUE TITLE
Appindicator support

### ISSUE THREAD

**Issue by vancez** [flathub/com.spotify.Client#257]
https://aur.archlinux.org/packages/spotify uses deb package as source which has appindicator support, may be we can also use deb package instead of snap?

**Comment by TingPing** [comment]
I can at least confirm packaging `libapindciator-gtk3` does not work with our current version.

Maybe it is only enabled in the deb release, which is odd.

**Comment by Erick555** [comment]
Flatpak spotify is at 1.2.13.661 while AUR is at 1.2.20.1210.

**Comment by TingPing** [comment]
While this has landed in the new release, its pretty janky and broken. Not sure if an upstream issue what.
