### ISSUE TITLE
Tray icon doesn't show full menu

### ISSUE THREAD

**Issue by alosarjos** [flathub/com.spotify.Client#262]
Hi!

After todays update, Spotify now shows a tray icon, but seems to be something wrong with it?

![imagen](https://github.com/flathub/com.spotify.Client/assets/29999427/de8d4633-79bd-4f29-af18-94c0861991e2)

**Comment by slagiewka** [comment]
Seems the same is true for the package built from deb in AUR: https://aur.archlinux.org/packages/spotify#comment-938810

KDE + Flatpak experience is the same https://github.com/flathub/com.spotify.Client/pull/260#issuecomment-1774032793

**Comment by TingPing** [comment]
The icon name it sets is `spotify-linux-32`, which can't work with Flatpak.

Would have to hack around it.

**Comment by TingPing** [comment]
Next update you'll see a proper icon: https://github.com/flathub/com.spotify.Client/commit/65d48cf5fc64dd4527622fd2d65890e10b7b6223

**Comment by slagiewka** [comment]
Icon is there 
![image](https://github.com/flathub/com.spotify.Client/assets/11974489/d44c0ff9-58aa-4347-ab27-0f342f948949)

But I've no idea why it doesn't show up the same as other apps - always visible. Or at least visible when playing.

**Comment by alosarjos** [comment]
Also can confirm Icon showing on Gnome, will check if I can somehow get a bit smaller version so it fits with the rest. Thanks a lot @TingPing 

![image](https://github.com/flathub/com.spotify.Client/assets/29999427/bb30b7f2-8f93-44db-a0cf-4c539d382d42)

**Comment by Bartwillemsen** [comment]
Can conform the icon is there, but minimized it's a bit useless. Only the exit option is there, with no way to restore the window from there. Not sure if this is the case upstream (unflatpakked version) as well.

![image](https://github.com/flathub/com.spotify.Client/assets/1550822/387475c8-eeb8-427c-8599-c93fb07fbe5b)

**Comment by slagiewka** [comment]
> Can confirm the icon is there, but minimized it's a bit useless. Only the exit option is there, with no way to restore the window. Not sure if this is the case upstream (unflatpakked version) as well.

This must be something with GNOME or the extension for tray.

KDE: 
![image](https://github.com/flathub/com.spotify.Client/assets/11974489/b07f609f-7ded-41dc-9802-96960bf997fc)

**Comment by alosarjos** [comment]
Fine here on Gnome too 

![image](https://github.com/flathub/com.spotify.Client/assets/29999427/0784f198-342f-40d1-a064-e89ff1e240b2)

**Comment by Bartwillemsen** [comment]
> This must be something with GNOME or the extension for tray.

Hmm ok, yeah it's pretty weird, the "minimize to tray" option is there when the window is open. If there is any way I can help figure it out or get in touch with the right people for this, please tell me :)

**Comment by gtirloni** [comment]
I've posted more details about the minimize to tray issue here: https://community.spotify.com/t5/Desktop-Linux/Close-button-should-minimize-the-Spotify-window-Spotify-won-t/m-p/5807256/highlight/true#M22511

**Comment by TingPing** [comment]
This was fixed at some point.
