### ISSUE TITLE
No tray icon on Linux Mint 21.2

### ISSUE THREAD

**Issue by ghost** [flathub/com.spotify.Client#270]
Currently using Linux Mint 21.2 and the tray icon just isn't there. It happens with the deb version as well, maybe I have to submit an issue in another place?

(using the latest spotify version)
![image](https://github.com/flathub/com.spotify.Client/assets/142275770/ef8491f8-d886-48aa-bb0d-76949a9357e9)

**Comment by TingPing** [comment]
Does your tray support StatusNotifiers (sometimes called AppIndicators)?

**Comment by wcw2x** [comment]
Sorry about the 3 days interval.

> Does your tray support StatusNotifiers (sometimes called AppIndicators)?

I guess... Every app that has support (except Spotify) does show a tray icon, Steam can be used as an example.

**Comment by gtirloni** [comment]
For anyone using GNOME, try an extension like [AppIndicator and KStatusNotifierItem Support](https://extensions.gnome.org/extension/615/appindicator-support/).

I spent so much on this a few years ago and I can't remember the details anymore. I think GNOME doesn't have tray icons anymore by default.

It seems you might be using LXDE/XFCE though?

This may seem like a dumb question, but have you enabled Spotify to minimize to tray in Settings? It's not enabled by default and the icon only appears after the first time you close the window (at least for me on GNOME). Reported here: https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by TingPing** [comment]
Mint uses Cinnamon by default.

Anyway the user deleted their account, so I'm going to close this.
