### ISSUE TITLE
Spotify not available on Fedora 39 Asahi

### ISSUE THREAD

**Issue by TonyBostonTB** [flathub/com.spotify.Client#273]
I did add the flatpak remote
```
➜  ~ flatpak remotes
Name    Options
fedora  system,oci
flathub system
```

Though, flatpak can't seem to find the package

```
➜  ~ flatpak install com.spotify.Client
Looking for matches…
error: No remote refs found for ‘com.spotify.Client’
```

**Comment by Erick555** [comment]
Spotify is x86-64 app only.

**Comment by TonyBostonTB** [comment]
Oh, it's THAT easy. Then sorry for the noise.

**Comment by Renner0E** [comment]
@TonyBostonTB you might enjoy reading [this](https://www.da.vidbuchanan.co.uk/blog/netflix-on-asahi.html)
