### ISSUE TITLE
(at least) opt-in for wayland support

### ISSUE THREAD

**Issue by ahjolinna** [flathub/com.spotify.Client#275]
follow up on previous discussion in issue https://github.com/flathub/com.spotify.Client/issues/239#issuecomment-1968125266, I'm suggesting the addition of Wayland support.

Enabling Wayland support, even optionally, would significantly enhance the user experience, especially for NVIDIA users who currently experience xwayland flickering and it would lead to a smoother and more stable performance overall.

I did notice a minor issue with the display of generic Wayland icons, but I believe this can be addressed

**Comment by LoneWolf4713** [comment]
I second this, on my Arch Linux machine, spotify running under XWayland takes 800MB - 1GB of memory, that is too much for a music player..... but I've had experiences where native wayland version of some apps consumed way less memory than Xwayland versions. 
I'm on Arch Linux with Hyprland. Running Spotify Flatpak.

**Comment by Erick555** [comment]
Note that everyone can opt-in already by adding relevant flags in [config](https://github.com/flathub/com.spotify.Client?tab=readme-ov-file#making-flags-persistent)

**Comment by justin13888** [comment]
> I second this, on my Arch Linux machine, spotify running under XWayland takes 800MB - 1GB of memory, that is too much for a music player..... but I've had experiences where native wayland version of some apps consumed way less memory than Xwayland versions. I'm on Arch Linux with Hyprland. Running Spotify Flatpak.

True! Didn't even notice it until you mentioned it lol. The biggest gripe for me is that in my multi-monitor setup, I'm forced to use fractional scaling which means blurry text on XWayland. I'm running GNOME 45 on Fedora 39 Workstation

**Comment by justin13888** [comment]
> Note that everyone can opt-in already by adding relevant flags in [config](https://github.com/flathub/com.spotify.Client?tab=readme-ov-file#making-flags-persistent)

I haven't been able to get Wayland to work. What command were you using?

This command wouldn't open any window: `flatpak run com.spotify.Client --enable-features=UseOzonePlatform --ozone-platform=wayland`

This command would hang up my desktop environment (GNOME 45 on Wayland): `flatpak run --socket=wayland com.spotify.Client --enable-features=UseOzonePlatform --ozone-platform=wayland`

For reference, I'm running version the latest version as of writing (version 1.2.31) on FlatHub and the Spotify snap version works besides improperly styled window decoration.

**Comment by Erick555** [comment]
To match what discord does (and what this issue proposes) try:

`flatpak run --socket=wayland com.spotify.Client --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto`

**Comment by LoneWolf4713** [comment]
Hi,  @justin13888 's answer is correct and this below produces no window. 
`❯ flatpak run com.spotify.Client --enable-features=UseOzonePlatform --ozone-platform=wayland

/app/extra/bin/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
~
❯ [spotifywm] attached to spotify
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify`


but as @Erick555 's answer produces a window that is still running in XWayland, here is the output:
 `❯ flatpak run --socket=wayland com.spotify.Client --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto

/app/extra/bin/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
~
❯ [spotifywm] attached to spotify
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify
[spotifywm] spotify window a00004 found
/proc/self/exe: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /proc/self/exe)
~
❯ [spotifywm] attached to spotify
[spotifywm] spotify window 1000007 found
/app/bin/spotify: line 45: Xlib.xauth:: command not found`


can anybody tell what I'm doing wrong here..?!

**Comment by Erick555** [comment]
You may try to force wayland by:
`flatpak run --socket=wayland --nosocket=x11 com.spotify.Client --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto`

**Comment by LoneWolf4713** [comment]
None of the solutions on this page worked for me. I guess the Flatpak version doesn't support Wayland in a stable way yet. I ended up installing spotify AUR Package (not spotify-launcher). and it launches in native wayland beautifully with command:
`❯ spotify --enable-features=UseOzonePlatform --ozone-platform=wayland`

Also, it's resource usage is way less than Flatpak version too. @justin13888 . Around 300MB as compared to 700MB-1.5GB of Flatpak version. 
I guess you can install AUR Version on any distro with a little tweaking.

**Comment by Erick555** [comment]
> I guess the Flatpak version doesn't support Wayland in a stable way yet. I ended up installing spotify AUR Package (not spotify-launcher).

You may note Flatpak has exact same spotify versions as AUR and snap.

**Comment by ahjolinna** [comment]
here is a fix for cursor scaling on wayland, for those who have HIDPI screen
`--env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons`

https://github.com/electron/electron/issues/19810

**Comment by ahjolinna** [comment]
I used this and it works for me

```
flatpak run --branch=stable --socket=wayland --arch=x86_64 --command=/app/extra/bin/spotify --file-forwarding com.spotify.Client --enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --enable-features=UseSkiaRenderer --ozone-platform=wayland --disable-gpu-sandbox '--enable-features=UseSkiaRenderer,WaylandWindowDecorations
' @@u %U @@
```
... not sure if all of these are needed, anyway : `--disable-gpu-sandbox` is only needed if you are using the nvidia drivers

**Comment by hoshsadiq** [comment]
When running with all of this, my cursor is in the wrong place. It's the correct size and theme, but the hovers and clicks register in different places from where my cursor is. In some cases, it's a couple of inches (15 inch screen) to the bottom right of the cursor, but in others places it's 4-5 inches away. I do get some errors when running on the command line:

```
$ flatpak run --user --socket=wayland --nosocket=x11 --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons com.spotify.Client
/app/extra/bin/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
[spotifywm] attached to spotify

Traceback (most recent call last):
  File "/app/bin/set-dark-theme-variant.py", line 11, in <module>
    disp = Xlib.display.Display()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.11/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/Xlib/support/unix_connect.py", line 59, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[spotifywm] attached to spotify
[spotifywm] attached to spotify
Opening in existing browser session.
libnotify-Message: 10:44:28.035: App Name is not available when using Portal Notifications
```

**Comment by justin13888** [comment]
> None of the solutions on this page worked for me. I guess the Flatpak version doesn't support Wayland in a stable way yet. I ended up installing spotify AUR Package (not spotify-launcher). and it launches in native wayland beautifully with command: `❯ spotify --enable-features=UseOzonePlatform --ozone-platform=wayland`
> 
> Also, it's resource usage is way less than Flatpak version too. @justin13888 . Around 300MB as compared to 700MB-1.5GB of Flatpak version. Hence it feels a lot snappier and faster than the Flatpak counterpart. I guess you can install AUR Version on any distro with a little tweaking.

Interesting. I didn't notice how much RAM it's using until you mentioned!

**Comment by justin13888** [comment]
> I used this and it works for me
> 
> ```
> flatpak run --branch=stable --socket=wayland --arch=x86_64 --command=/app/extra/bin/spotify --file-forwarding com.spotify.Client --enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --enable-features=UseSkiaRenderer --ozone-platform=wayland --disable-gpu-sandbox '--enable-features=UseSkiaRenderer,WaylandWindowDecorations
> ' @@u %U @@
> ```
> 
> ... not sure if all of these are needed, anyway : `--disable-gpu-sandbox` is only needed if you are using the nvidia drivers

Thanks! I could confirm this also works on my system (Fedora 39, with MESA AMD drivers)

**Comment by daenney** [comment]
Does anyone have cursor issues with this? I don't mean the cursor theme missing, I mean the cursor not clicking where you think it should be. It seems to be off by quite a lot, resulting in completely different UI elements being activated that aren't under the cursor.

**Comment by fugkco** [comment]
@daenney yes, I commented in #239, but maybe here is more relevant.

**Comment by hoshsadiq** [comment]
I have the same issue, I commented in #239, but maybe this thread is more relevant to it.

**Comment by FrankBrown321** [comment]
[How to see spotify stats](https://spotipie.com/)
To see your Spotify stats, use Spotify Wrapped for annual highlights of your top songs, artists, and genres. For detailed, regular insights, try third-party sites like SpotiPie. Log in with your Spotify account to view your most-played tracks, hours listened, and more. Artists can use Spotify for Artists for detailed analytics.

**Comment by FrankBrown321** [comment]
> Hi, @justin13888 's answer is correct and this below produces no window.
> 
> ```
> ❯ flatpak run com.spotify.Client --enable-features=UseOzonePlatform --ozone-platform=wayland
> 
> /app/extra/bin/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
> ~
> ❯ [spotifywm] attached to spotify
> /app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
> /app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
> [spotifywm] attached to spotify
> [spotifywm] attached to spotify 
> ```
> 
> but as @Erick555 's answer produces a window that is still running in XWayland, here is the output:
> 
> ```
>  ❯ flatpak run --socket=wayland com.spotify.Client --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto
> 
> /app/extra/bin/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
> ~
> ❯ [spotifywm] attached to spotify
> /app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
> /app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
> [spotifywm] attached to spotify
> [spotifywm] attached to spotify
> [spotifywm] spotify window a00004 found
> /proc/self/exe: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /proc/self/exe)
> ~
> ❯ [spotifywm] attached to spotify
> [spotifywm] spotify window 1000007 found
> /app/bin/spotify: line 45: Xlib.xauth:: command not found
> ```
> 
> can anybody tell what I'm doing wrong here..?!
[How to see spotify stats](https://www.spotipie.com/)
To see your Spotify stats, use Spotify Wrapped for annual highlights. For detailed insights, try SpotiPie. Log in with spotipie.com to view your top tracks and hours listened. Artists use Spotify for Artists.

**Comment by justin13888** [comment]
> > Hi, @justin13888 's answer is correct and this below produces no window.
> > ```
> > ❯ flatpak run com.spotify.Client --enable-features=UseOzonePlatform --ozone-platform=wayland
> > 
> > /app/extra/bin/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
> > ~
> > ❯ [spotifywm] attached to spotify
> > /app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
> > /app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
> > [spotifywm] attached to spotify
> > [spotifywm] attached to spotify 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but as @Erick555 's answer produces a window that is still running in XWayland, here is the output:
> > ```
> >  ❯ flatpak run --socket=wayland com.spotify.Client --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto
> > 
> > /app/extra/bin/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
> > ~
> > ❯ [spotifywm] attached to spotify
> > /app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
> > /app/extra/share/spotify/spotify: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
> > [spotifywm] attached to spotify
> > [spotifywm] attached to spotify
> > [spotifywm] spotify window a00004 found
> > /proc/self/exe: /usr/lib/x86_64-linux-gnu/libcurl.so.4: no version information available (required by /proc/self/exe)
> > ~
> > ❯ [spotifywm] attached to spotify
> > [spotifywm] spotify window 1000007 found
> > /app/bin/spotify: line 45: Xlib.xauth:: command not found
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > can anybody tell what I'm doing wrong here..?!
> > [How to see spotify stats](https://www.spotipie.com/)
> > To see your Spotify stats, use Spotify Wrapped for annual highlights. For detailed insights, try SpotiPie. Log in with spotipie.com to view your top tracks and hours listened. Artists use Spotify for Artists.

About the second command, setting platform hint to auto doesn't guarantee that Ozone uses Wayland.

I got it working on Fedora  39 Workstation as mentioned previously but the other problem is that the client-side window decoration on Spotify is hidious. On GNOME, since server side decoration has been rejected, the only solution that would work on GNOME/Mutter would be for Spotify devs to add back a GTK decoration (or perhaps it could be possible to modify the community's Flatpak version?)

**Comment by TingPing** [comment]
Done in 5248553d4a3c01dce38929c108307cb7a30ed42a

**Comment by d3vilguard** [comment]
Why is my mouse so small with this :D (125 fractional, Gnome 47, wayland opt-in)
![image](https://github.com/user-attachments/assets/04d0d938-892c-4f8a-ba23-8123690b8fc5)

**Comment by TingPing** [comment]
On Wayland the application controls the cursor. It is using the wrong size, probably nothing we can do about it.

**Comment by ahydronous** [comment]
On Wayland, the drop-down menu for things like audio quality also tries to open up in a separate tiny pop-up window which then immediately closes.
