### ISSUE TITLE
Prefer deb package instead of snap

### ISSUE THREAD

**Issue by farribeiro** [flathub/com.spotify.Client#278]
The app have a another way of distribuition... I think it's pertinent to prefer it 

---

## Debian / Ubuntu
Spotify for Linux is also released as a Debian package. Our aim is that it should work with the latest Long Term Support release of Ubuntu, but we will try to make it work for other releases of Ubuntu and Debian as well.

You will first need to configure our debian repository:

```bash
curl -sS https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
```

Then you can install the Spotify client:

```bash
sudo apt-get update && sudo apt-get install spotify-client
```

https://www.spotify.com/en/download/linux/

**Comment by lionirdeadman** [comment]
IIRC The snap version had more updates which was why it was preferred.

If someone wanted to do this, they should have a look at https://github.com/flathub-infra/flatpak-external-data-checker?tab=readme-ov-file#debian-repo-checker

**Comment by Erick555** [comment]
Flatpak source was moved to snap because the deb was unreliable (it was missing releases from time to time).

**Comment by farribeiro** [comment]
Ok... Thanks for the info
