### ISSUE TITLE
Proxy settings are not saved

### ISSUE THREAD

**Issue by amirkazemzade** [flathub/com.spotify.Client#280]
## Description
After changing proxy settings, there is only a `Restart App` button for saving it. After clicking it, the app will close and after relaunching (manually, does not run again automatically), the proxy settings are set back to default.

### Before clicking `Restart App`
![image](https://github.com/flathub/com.spotify.Client/assets/76568952/afc11533-95c4-4397-b48d-af11ac9523dc)

### After relaunching manually
![image](https://github.com/flathub/com.spotify.Client/assets/76568952/97010ff3-deae-4c2c-a71a-ee4a0ed1f529)

**Comment by guihkx** [comment]
How did you make that modal dialog appear?

Because here, proxy settings are available by clicking on your photo (on the top right corner), clicking on Settings, and then scrolling the page all the way down.

Additionally, these settings in specific are automatically saved to `~/.var/app/com.spotify.Client/config/spotify/prefs`, as soon as you change add/remove any character of your proxy settings.

**Comment by amirkazemzade** [comment]
The modal dialog is the kind of view you would get when you are not logged in yet, and the only setting available before logging in is the proxy settings.

![image](https://github.com/flathub/com.spotify.Client/assets/76568952/4f1093d9-ef9d-4d77-9f07-4f6e9351eba8)

By the way, there is no `spotify` folder in my  `~/.var/app/com.spotify.Client/config/` directory!

![image](https://github.com/flathub/com.spotify.Client/assets/76568952/11fc5c6f-f032-442e-9ed8-4a4adf127e96)

**Comment by guihkx** [comment]
Thanks for that info, I can reproduce the problem now.

This looks like a genuine bug in the app to me.

I found a workaround for it, though: Just manually create the `spotify` folder at any time, and then the app will be able to create the `prefs` file inside of it, i.e.:

```bash
mkdir -p ~/.var/app/com.spotify.Client/config/spotify
```

**Comment by amirkazemzade** [comment]
The workaround worked nicely. Thanks.

I'll put some info here that might help you solve the bug:
OS: `Fedora Workstation`
Version: `39`
Install Method: `Fedora Software Store`

**Comment by guihkx** [comment]
I'm glad that worked for you, but allow me to clarify a misunderstanding: This Flatpak package is not officially endorsed (or supported) by Spotify. 

We're all just community volunteers. :)

In any case, they seem to have an [official channel](https://community.spotify.com/t5/Desktop-Linux/bd-p/desktop_linux) where you can report bugs, so you could do that, if you want.

However, I think that adding a workaround here for this would be really trivial. I'll send a pull request for review.

**Comment by amirkazemzade** [comment]
@guihkx I knew it was not official, but I thought this bug was related to the Flatpak version.
Just asking, is this a port of the Debian version that is officially supported?

**Comment by guihkx** [comment]
No, this is a repackage of the [official Snap package](https://snapcraft.io/spotify).
