### ISSUE TITLE
Fractional Scaling not detected in Plasma 6 Wayland

### ISSUE THREAD

**Issue by jackwalten** [flathub/com.spotify.Client#283]
As stated in the title, scaling is not detected when running in plasma 6 wayland, and as a workaround one has to use ``--force-device-scale-factor``.

**Comment by TingPing** [comment]
You can update this script to handle this case: https://github.com/flathub/com.spotify.Client/blob/master/get-scale-factor.py

**Comment by Erick555** [comment]
I think it [never worked](https://github.com/flathub/com.spotify.Client/issues/113) with fractional scaling on any Plasma version. Setting `--force-device-scale-factor` or simply use `ctrl+` is the way to go.

**Comment by jackwalten** [comment]
It is pretty trivial to add support, but I think we will need read permissions for xdg-config/kdeglobals or xdg-config/kwinrc to make it possible by default. And I don't think adding desktop-specific fixes is a good practice. If someone can help me get the scale factor without reading from the files, it would be very greatly appreciated.

**Comment by TingPing** [comment]
Should be fixed by 20095e98bb3a8dcabbba46052202f2ae39daf7b3

Let us know if there are still any issues.
