### ISSUE TITLE
Spotify Flatpak doesn't respect "Close button should minimize" setting and immediately closes upon clicking "X"

### ISSUE THREAD

**Issue by RVFET** [flathub/com.spotify.Client#293]
It's so god damn frustrating. I have to keep the window open to listen to music? There's no point of having this app then, since open.spotify.com does the exact same thing. I'm so frustrated and annoyed by the fact there's only a single reddit thread about this issue with no fix/workaround.

## Hardware Information:
- **Hardware Model:**                              Lenovo Legion Pro 5 16IRX8
- **Memory:**                                      32.0 GiB
- **Processor:**                                   13th Gen Intel® Core™ i9-13900HX × 32
- **Graphics:**                                    Intel® Graphics (RPL-S)
- **Graphics 1:**                                  NVIDIA Corporation AD106M [GeForce RTX 4070]
- **Disk Capacity:**                               1.0 TB

## Software Information:
- **Firmware Version:**                            KWCN46WW
- **OS Name:**                                     Fedora Linux 40 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.9.12-200.fc40.x86_64

**Comment by TingPing** [comment]
This works fine for me.

I do have the extension for a tray (https://extensions.gnome.org/extension/615/appindicator-support/).

**Comment by RVFET** [comment]
> I do have the extension for a tray (https://extensions.gnome.org/extension/615/appindicator-support/).

Thank you a billion times, man. It works flawlessly.
