### ISSUE TITLE
Bad performance on Chrome OS Flex Linux system

### ISSUE THREAD

**Issue by rainbowdash5** [flathub/com.spotify.Client#294]
When using the Spotify Flatpak app for the Linux system for Chrome OS Flex, songs lag and skip in the background when loading web pages in the Google Chrome browser. Once the website fully loads songs play normal. I have also tried this on the deb version of Spotify and i'm experiencing the same problem. I am using Chrome OS Flex Version 126.0.6478.222 (Official Build) (64-bit). My system specs are Intel Celeron N4020 CPU @ 1.10GHz (2 threads, 2.80GHz), 4gb of ram and 128gb of storage

**Comment by TingPing** [comment]
The Spotify app doesn't enable hardware acceleration (https://github.com/flathub/com.spotify.Client/issues/223).

There are flags you can play around with to try and test but Spotify themselves don't enable or support them. I've seen other Chromium based projects break when enabling these features so its not a simple toggle for the package.

So I don't really think anything is actionable here. You just have very slow hardware and Spotify relies on the CPU.

The general topic can be tracked in #223.
