### ISSUE TITLE
Unkown UI

### ISSUE THREAD

**Issue by iFabse** [flathub/com.spotify.Client#296]
![Bildschirmfoto vom 2024-09-16 19-27-52](https://github.com/user-attachments/assets/7bbc6c6f-be65-4e13-8155-50ecba9a899e)

Hi, 
I've installed spotify with flatpak : `flatpak install spotify`

and got this output: (sorry some parts in German)

`Suchen nach Übereinstimmungen …
Found ref ‘app/com.spotify.Client/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: 

com.spotify.Client Berechtigungen:
    ipc                    network                pulseaudio               x11            dri
    file access [1]        dbus access [2]        bus ownership [3]        tags [4]

    [1] xdg-music:ro, xdg-pictures:ro
    [2] org.gnome.SessionManager, org.gnome.SettingsDaemon.MediaKeys, org.kde.StatusNotifierWatcher
    [3] org.mpris.MediaPlayer2.spotify
    [4] proprietary

        KENNUNG                     Zweig           Op          Gegenstelle          Herunterladen
 1. [✓] com.spotify.Client          stable          i           flathub              200,5 MB / 201,0 MB

Installation abgeschlossen.
`

Does anybody know how to change this theme / look?

Thanks :)

**Comment by TingPing** [comment]
I don't understand your question, that is how Spotify looks, it has nothing to do with this package.

**Comment by iFabse** [comment]
Oh okay, this is new to me lol

**Comment by TingPing** [comment]
I feel like it has been this way for a very long time.

One thing you might not notice is you can resize the playlist bar on the left to show text.

**Comment by iFabse** [comment]
Yeah on my other device there is not the new design. Don't know why. Have to live with it. Thanks ;)
