### ISSUE TITLE
Spotify: url handler not pushed in metadata

### ISSUE THREAD

**Issue by freechelmi** [flathub/com.spotify.Client#308]
It seems that the info that spotify can handle spotify: urls is not pushed correctly which leads to a user that wants to open a spotify URL not proposed the spotify application in gnome-software  

![Capture d’écran du 2024-10-18 14-40-03](https://github.com/user-attachments/assets/f602ef10-5d18-4761-b833-e0fb4d97497c)

**Comment by Erick555** [comment]
I see it's set in desktop file: https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.desktop#L9

**Comment by bbhtt** [comment]
It's in the metadata too. What version of gnome software do you have? It seems to work fine for me with GNOME Software 46.5

![image](https://github.com/user-attachments/assets/753ff3f0-dd0a-4738-9c4c-251abe0f4404)

**Comment by bbhtt** [comment]
Or is that something else? Then you should contact those developers.

**Comment by Erick555** [comment]
Just to be sure: are you using spotify from flatpak?

**Comment by freechelmi** [comment]
Yes , we are talking about the flatpaks discovery here :-) 

Yes works perfect on Ubuntu 24.04 Gnome 46

22.04 has Gnome 42 , I know it's old but we still have a lot of clients on 22.04 For at least 2 years 

I guess Gnome-software 42 did not read ignore some metadata ?

Yes I know we are off topic here :-) , let's close it then
