### ISSUE TITLE
Lost window decorations

### ISSUE THREAD

**Issue by Yajo** [flathub/com.spotify.Client#33]
Not sure exactly when and how, but spotify is now without window decorations.

I can't resize it or move it, not even using GNOME hotkeys for the matter...

Closing and reopening it doesn't help.

**Comment by TingPing** [comment]
Can't reproduce. Probably nothing relevant to Flatpak anyway.

**Comment by Yajo** [comment]
Can you imagine where the bug could come from?

**Comment by Yajo** [comment]
Not sure what it was, but I uninstalled Spotify from GNOME Software Center and reinstalled it, and it works now.

**Comment by Yajo** [comment]
It started happening again.

I opened it from terminal and got these logs:

```
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
[0427/080455.532570:ERROR:sandbox_linux.cc(344)] InitializeSandbox() called with multiple threads in process gpu-process.
```

Do they give you any hints?

Thanks!

**Comment by tomasz-oponowicz** [comment]
I have the same issue from time to time.

I've just noticed that you can restore window decorations by entering and exiting full screen mode. Maybe this is a Spotify issue which randomly enforces full screen mode on startup.

**Comment by TingPing** [comment]
Those warnings are unrelated. Really this has nothing to do with this package.
