### ISSUE TITLE
Exiting spotify does not kill playing

### ISSUE THREAD

**Issue by montvid** [flathub/com.spotify.Client#42]
Exiting spotify does not kill playing on fedora 28 workstation. After exiting spotify the music is still playing, the notification is still present but does not work no pause, forward, backward. The process spotify is still alive in system monitor. running spotify again starts a different process.

**Comment by montvid** [comment]
Seems a random bug - can't reproduce it now after reboot.

**Comment by montvid** [comment]
Seems a random bug - can't reproduce it now after reboot.

**Comment by montvid** [comment]
It happened yesterday again on Debian 10 using flatpak. Exiting the client in gui does not kill the process. This happens very rarely.

**Comment by TingPing** [comment]
Whatever your issue may be it has nothing to do with this package.
