### ISSUE TITLE
Filesystem permissions too restrictive

### ISSUE THREAD

**Issue by jreznik** [flathub/com.spotify.Client#47]
Currently, Spotify filesystem permissions only allows read-only access to the xdg-music directory but it's too restrictive as for example, it's possible to upload own playlist's cover art or change profile picture. And users usually store pictures in the xdg-pictures directory and it can be very confusing when it's not available and it's a feature of Spotify client (workaround is to move desired picture to the xdg-music directory but...). Please add xdg-pictures as read-only directory to the filesystem permissions list.

**Comment by TingPing** [comment]
You can just run `flatpak override --user --filesystem=xdg-pictures:ro com.spotify.Client`

**Comment by jreznik** [comment]
I know I can override it from CLI - but I believe the default behavior should be changed in a way that the app is fully usable without the need to do it. Especially if you consider end users of Spotify client (who might even not know what Flatpak is).
