### ISSUE TITLE
Media controls sometimes don’t work

### ISSUE THREAD

**Issue by fbruetting** [flathub/com.spotify.Client#49]
Since a few weeks, it happens sometimes, that the media controls of my keyboard don’t work (anymore). When I start Lollypop, they work fine. I’m running Fedora 28 Silverblue.

**Comment by TingPing** [comment]
I think this is just a long standing Spotify bug.

**Comment by barthalion** [comment]
Yeah, I remember it also from unsandboxed version on Arch.

**Comment by fbruetting** [comment]
Normally this was resolved via rebooting the machine.

Since a few days, rebooting sadly doesn’t solve this issue anymore. Throughout the last days, I saw some Flatpak programs requesting access to the media keys – could it be that the runtimes now restrict media key access so that this privilege must now be explicitly requested from the Spotify flatpak?

**Comment by TingPing** [comment]
MPRIS works fine here.

MediaKeys are a separate problem that at this rate will just never be fixed by Spotify. GNOME provides mediakey support to MPRIS clients so it happens to work.

**Comment by fbruetting** [comment]
However, with the latest Fedora & Flatpak updates the sporadic bugs have changed into not working at all… :/

I sadly can’t rollback/undo the Fedora updates, but those are the contents, if someone else also has this issue and may be able to inspect:
```
glibc[-common,devel,headers,langpack-en] 2.27-30 ⇒ 2.27-32
libgs 9.23-5 ⇒ 9.23-6
libnghttp2 1.32.0-1 ⇒ 1.32.1-1
libnsl-2.27.30 ⇒ 2.27.32
libssh 0.8.1-4 ⇒ 0.8.2-1
wget 1.19.5-1 ⇒ 1.19.5-5
```

**Comment by TingPing** [comment]
Your host updates (beyond GNOME-Shell) are not relevant at all.

**Comment by TingPing** [comment]
Also just wanted to note I am on X11 if Spotify maybe binds keys via that. Can't test Wayland.

**Comment by fbruetting** [comment]
> Your host updates (beyond GNOME-Shell) are not relevant at all.

Wasn’t sure about that. I don’t have this problem on my F28-Silverblue/Wayland station, just on my F28-proper/X11 station… I’ll test Wayland tomorrow on that last machine and see what the next days bring.

**Comment by fbruetting** [comment]
I just have this problem again. I can restart Spotify several times (I made sure that all processes were killed each time) with the media controls not getting to work again. However, I can still control Spotify fine via MPRIS (“Media player indicator” shell extension) and KDE Connect. So solely the media keys don’t work.

With the state of the application being properly reset each time, that seems more like a problem caused by the host/Gnome and/or Flatpak (portal), instead of an upstream Spotify bug. Further evidence is that restarting Gnome solves this issue – so somehow the state of Gnome/Flatpak is corrupt.

**Comment by fbruetting** [comment]
I really believe that this is due to Flatpak or this repo here. Just 20 seconds ago I encountered a state, where I quit Spotify, the application state went to inactive in my DashToDock and still the music continued to play!

I then was able to start a second instance of Spotify via clicking on the icon in the Dock, it lighted up again and I was able to play another song in parallel to the quasi-zombie-state old instance. Then I tested my media keys, and they stopped working. So there really seems to be a glitch state, where something really doesn’t work right. Or am I wrong here?

**Comment by TingPing** [comment]
Flatpak just isn't relevant to how media keys are handled.

Either:

1. The application exposes MPRIS and GNOME-Shell handles the bindings
2. The application uses gnome-setting-daemons mediakey interface
3. It directly grabs the input from x11

Note how Flatpak is not in the chain for any of those features.

I believe Spotify uses 2 *but* it uses the wrong bus name so it doesn't work on anything newer than GNOME 3.18 or so.

So then it must just be relying on 1. One issue with relying on that is the feature completely breaks when you have multiple players (who gets the keys? nobody knows).

**Comment by fbruetting** [comment]
Yeah, I understand that Flatpak doesn’t directly influence this. But with having had one zombie instance in parallel to a regular instance showed me that Flatpak might not handle the application lifecycle correctly – which might have caused this, as then two applications might having bus collisions or so.

I don’t know anything about those internals, but I assume that having two instances of Spotify in parallel – with one being uncontrollable, as there was neither a window nor was I able to control it via the dock icon – is surely not intended behavior and could have caused subsequent faults.

**Comment by TingPing** [comment]
Again its probably not Flatpak its just Spotify being bad. Sure you could make a wrapper process that ensures everything is cleaned up and one process exists but first verify thats actually the problem.

**Comment by fbruetting** [comment]
Seems to be gone with Fedora 30 / Gnome 3.32, for the record. 🥳
