### ISSUE TITLE
Can't login with Facebook

### ISSUE THREAD

**Issue by alexandrevicenzi** [flathub/com.spotify.Client#5]
It only opens an empty window when I click the button.

```
$ flatpak run com.spotify.Client                  
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)

(process:2): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
[0929/112845.543609:ERROR:cert_verify_proc_nss.cc(902)] CERT_PKIXVerifyCert for spclient.wg.spotify.com failed err=-5992
[0929/112850.120149:ERROR:cert_verify_proc_nss.cc(902)] CERT_PKIXVerifyCert for redirector.gvt1.com failed err=-5992
[0929/112850.698102:ERROR:cert_verify_proc_nss.cc(902)] CERT_PKIXVerifyCert for www.facebook.com failed err=-5992

```

**Comment by timhowes** [comment]
Seems to be failing to verify certificates. Might be an issue with the nss version:
https://github.com/flathub/com.spotify.Client/blob/b4dffd466befc6cd9d38ddb7d8865cc1141af9ab/com.spotify.Client.json#L56

**Comment by TingPing** [comment]
Maybe just not configured to look for certs in the right place?

**Comment by timhowes** [comment]
The -5992 error means "not implemented", meaning the CERT_PKIXVerifyCert function is not found.
https://mozilla.github.io/python-nss-docs/nss.error-module.html

Might be similar to this problem from chromium?
https://bugs.archlinux.org/task/54387

**Comment by alexandrevicenzi** [comment]
@TingPing is this fix already on FlatHub? I can still reproduce this issue after updating Spotify.

**Comment by TingPing** [comment]
Give it maybe 10 more minutes: https://flathub.org/builds/#/builders/1/builds/526

**Comment by alexandrevicenzi** [comment]
@TingPing looks like the build is stuck :(

**Comment by TingPing** [comment]
Looks like it just finished.

**Comment by alexandrevicenzi** [comment]
It's working :tada: 

Thanks.
