### ISSUE TITLE
Update to 1.0.88.353

### ISSUE THREAD

**Issue by Vistaus** [flathub/com.spotify.Client#52]
A new version was released last week:

http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.88.353.g15c26ea1-14_amd64.deb

Could you please update this Flatpak? :)

**Comment by Erick555** [comment]
There are two different spotify releases: stable and testing. This flatpak follows stable releases.

https://github.com/flathub/com.spotify.Client/commit/09bddf77c6ddb9601aa69ddd533f71ab90948fef
https://github.com/flathub/com.spotify.Client/issues/43#issuecomment-394862537
https://github.com/flathub/com.spotify.Client/pull/40#issuecomment-386670374

**Comment by Vistaus** [comment]
I had received that update as a stable release via Snap and their repository (on a Debian-based system). So if it isn't stable, they shouldn't push it as such.

**Comment by Erick555** [comment]
Then you should report it to them, not here.
http://repository.spotify.com/dists/stable/non-free/binary-amd64/Packages
http://repository.spotify.com/dists/testing/non-free/binary-amd64/Packages
