### ISSUE TITLE
Remove access to org.gnome.SettingsDaemon

### ISSUE THREAD

**Issue by hadess** [flathub/com.spotify.Client#53]
The correct D-Bus name is `org.gnome.SettingsDaemon.MediaKeys`, and host implementations should be fixed instead of allowing access to a potentially dangerous daemon. See:
https://bugzilla.gnome.org/show_bug.cgi?id=781326#c8

**Comment by Erick555** [comment]
What do you mean by "host implementations should be fixed"? Is it enough to change ["--talk-name=org.gnome.SettingsDaemon"](https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.json#L19) to "--org.gnome.SettingsDaemon.MediaKeys" or is there something else to do?

**Comment by hadess** [comment]
> What do you mean by "host implementations should be fixed"? Is it enough to change "--talk-name=org.gnome.SettingsDaemon" to "--talk-name=org.gnome.SettingsDaemon.MediaKeys" or is there something else to do?

The application should only ever use `org.gnome.SettingsDaemon.MediaKeys` (both as a permission in the Flatpak manifest, and in the application code itself). No other changes are necessary. If things stop working for some users, they've found a bug in the host software/distribution, and should file a bug there.

**Comment by Erick555** [comment]
Well, it's rather hard to fill a bug to spotify. If you tested that spotify works with only change in manifest  then you can make pr here.

**Comment by TingPing** [comment]
Yea Spotify hasn't updated to the new name, I tested it recently.

**Comment by hadess** [comment]
> Yea Spotify hasn't updated to the new name, I tested it recently.

So it doesn't talk to anything. How about removing the access, and letting it be handled over MPRIS then?
