### ISSUE TITLE
Update to v1.0.89.313

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.spotify.Client#56]

**Comment by Lonsfor** [comment]
https://github.com/flathub/com.spotify.Client/issues/52#issuecomment-416289883

**Comment by TingPing** [comment]
I think I'm going to reverse that decision actually. It is the version Spotify ships on other platforms so we should probably just do so also.

**Comment by TingPing** [comment]
https://github.com/flathub/com.spotify.Client/commit/61ce0db4d87162879ebbf2ffff68e8171bea8fbd
