### ISSUE TITLE
neither taskbar icon nor systray icon appear on Ubuntu 16.04

### ISSUE THREAD

**Issue by trappedinspacetime** [flathub/com.spotify.Client#57]
I installed latest version of Spotify from `flathub` (Spotify version 1.0.72.117.g6bd7cc73). Unfortunately it doesn't show taskbar icon and systray icon. 
If I run it like

       flatpak run --command=sh com.spotify.Client

taskbar icon shows up but no systray icon again. 
It was well in the previous versions.

**Comment by TingPing** [comment]
I didn't know it has a systray? Looking through the logs I don't see it trying to make one.

Side note, the 32bit version of Spotify is dead and will never get another update.

**Comment by trappedinspacetime** [comment]
@TingPing Thank you for responding. I am sorry for my presupposition, I thought systray icon should have been there. I notice that Spotify has no systray icon. However, I installed 64 bit version of spotify, still no taskbar icon.

**Comment by trappedinspacetime** [comment]
I found a workaround for systray icon:

      kdocker -q -t -n "Spotify Free" -i /usr/share/icons/matefaenza/apps/48/spotify-linux-48x48.png & exit

**Comment by TingPing** [comment]
> I found a workaround for systray icon:

I presume you mean taskbar icon.

**Comment by TingPing** [comment]
Oh `kdocker` is a tool to make custom systrays, well that has nothing to do with this package of course.

**Comment by trappedinspacetime** [comment]
I mean `I found a workaround for adding a systray icon for `Spotify` but taskbar icon is still not present though it appears rarely. Adding a systray icon may be possible via python modules: https://gist.github.com/jmarroyave/a24bf173092a3b0943402f6554a2094d

**Comment by TingPing** [comment]
Ok well that has nothing to do with this package.
