### ISSUE TITLE
Crash on Manjaro after update

### ISSUE THREAD

**Issue by Shwasnine** [flathub/com.spotify.Client#59]
Hi, after the last update I have been trying to run the spotify but it returns me the "error: 2" message on the client. So when I was running via terminal, he gave me the following message:

```
$ flatpak run com.spotify.Client
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
Gtk-Message: 21:21:34.159: Failed to load module "canberra-gtk-module"
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[1001/212134.312304:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.
```
Here is the info on the application.

```
$ flatpak info com.spotify.Client
Ref: app/com.spotify.Client/x86_64/stable
ID: com.spotify.Client
Arq.: x86_64
Ramo: stable
Origem: flathub
ID de coleção: org.flathub.Stable
Data: 2018-09-15 15:07:43 +0000
Assunto: Restore XML header (abaa46a6)
Commit: 685f4d70813d5336b9c62c681851e35c07b7c909b7e9fb87e7ea1c2930e96ca2
Pai: 92194f0d39ac512b1b4581ea0aba608f6f81d36f017da628c717036e26fc110c
Localização: /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/685f4d70813d5336b9c62c681851e35c07b7c909b7e9fb87e7ea1c2930e96ca2
Tamanho instalado: 44,5 MB
Runtime: org.freedesktop.Platform/x86_64/18.08
Sdk: org.freedesktop.Sdk/x86_64/18.08
```

**Comment by Erick555** [comment]
> /app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
> Gtk-Message: 21:21:34.159: Failed to load module "canberra-gtk-module"
> /app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
> /proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
> [1001/212134.312304:ERROR:sandbox_linux.cc(378)] InitializeSandbox() called with multiple threads in process gpu-process.

All of those messages are normal. The actual error is somewhere else.

**Comment by Shwasnine** [comment]
I am running graphical hybrid on laptop. It's an intel core i5 along with an nvidia gt 640M

**Comment by Shwasnine** [comment]
Thank you!
I updated the table and everything is running perfectly!
