### ISSUE TITLE
Only Pictures folder is visible if you want to add local files

### ISSUE THREAD

**Issue by Zlopez** [flathub/com.spotify.Client#61]
I tried to add new local files to spotify, but currently spotify see only `Pictures` folder in my home, which doesn't make sense to me. If any folder should be visible for it, it should be `Music` folder.
![screenshot from 2018-10-27 16-24-55](https://user-images.githubusercontent.com/6943409/47605358-a30c8b00-da05-11e8-829b-d7aa19d832c8.png)

What is interesting, is that I can access plenty of directories in `/`. I'm not sure if this is even an issue, but if I'm not mistaken it should be sandboxed.
![screenshot from 2018-10-27 16-24-49](https://user-images.githubusercontent.com/6943409/47605380-e36c0900-da05-11e8-91dd-387e45057cc9.png)

**Comment by Zlopez** [comment]
Found out, the issue was on my side. I didn't had `XDG_MUSIC_DIR` specified in `.config/user-dirs.dirs`.

**Comment by TingPing** [comment]
> Found out, the issue was on my side. I didn't had `XDG_MUSIC_DIR` specified in `.config/user-dirs.dirs`.

For future readers: `xdg-user-dirs-update --set MUSIC /a/path/to/music`
