### ISSUE TITLE
Cannot login – error 17

### ISSUE THREAD

**Issue by jurf** [flathub/com.spotify.Client#63]
This started happening out of nowhere. Reporting this here just in case, because I have a suspicion that this is because of something different.

I’ll try a different network, because I can’t log in on my phone either for some reason, but it does work on my roommates’ devices.

![obrazok](https://user-images.githubusercontent.com/7472425/48149782-49d21080-e2bd-11e8-99ae-1c47d41a724f.png)

Silverblue 29.

**Comment by Erick555** [comment]
I've recently lost access to my account completely with Error code: 3 (Incorrect Username or Password) but I don't link it with flatpak.

You may try adding `--show-console` when running Spotify: `flatpak run --verbose com.spotify.Client --show-console` to see more output.

**Comment by jurf** [comment]
Thanks for the tip. `Connection error: login_region_mismatch`.
