### ISSUE TITLE
install fails on 404

### ISSUE THREAD

**Issue by vladimir152** [flathub/com.spotify.Client#66]
$ flatpak install flathub com.spotify.Client                                                                                                                                             
Installing in system:
com.spotify.Client/x86_64/stable flathub 747830fc58b7
  permissions: ipc, network, pulseaudio, x11, dri
  file access: xdg-music:ro, xdg-pictures:ro
  dbus access: org.freedesktop.Notifications, org.gnome.SessionManager, org.gnome.SettingsDaemon
  dbus ownership: org.mpris.MediaPlayer2.spotify
  tags: proprietary
Is this ok [y/n]: y
Installing: com.spotify.Client/x86_64/stable from flathub
[#=                  ] Downloading files: 1/1 569 bytes (284 bytes/s)
error: Failed to install com.spotify.Client/x86_64/stable: While downloading https://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.92.390.g2ce5ec7d-18_amd64.deb: Server returned status 404: Not Found

Failing through terminal and through software app on Fedora 29.

**Comment by BartolomeD** [comment]
Seems like spotify updated their repository with new versions: https://repository-origin.spotify.com/pool/non-free/s/spotify-client/

If we could update the old version with `spotify-client_1.0.94.262.g3d5c231c-9_amd64.deb` it should work. 

Don't know where to update that though.
