### ISSUE TITLE
Stuck in fullscreen

### ISSUE THREAD

**Issue by NeroVanbiervliet** [flathub/com.spotify.Client#67]
Spotify starts in fullscreen mode. There is no way to make it windowed.  

System: Ubuntu 18.10
Output of `flatpak info com.spotify.Client`
```
Ref: app/com.spotify.Client/x86_64/stable
ID: com.spotify.Client
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-10-25 15:38:09 +0000
Subject: Add 1.0.92.390 relase to appdata (31c3042f)
Commit: 747830fc58b7404546bea241b2708472de3f107a041d1bb386263b7eea74fae2
Parent: 685f4d70813d5336b9c62c681851e35c07b7c909b7e9fb87e7ea1c2930e96ca2
Location: /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/747830fc58b7404546bea241b2708472de3f107a041d1bb386263b7eea74fae2
Installed size: 44,5 MB
Runtime: org.freedesktop.Platform/x86_64/18.08
Sdk: org.freedesktop.Sdk/x86_64/18.08
```

**Comment by Erick555** [comment]
First of all update to latest version with `flatpak update`.

**Comment by NeroVanbiervliet** [comment]
Good point. I upgraded, but no cigar.

**Comment by ngmarchant** [comment]
I had the same issue. I think it's an upstream problem (see [here](https://community.spotify.com/t5/Desktop-Windows/Spotify-open-in-full-screen-cannot-access-taskbar-anymore/td-p/1044311)). Spotify will try to start with the same window dimensions as the last session. If your screen resolution changes (gets smaller) the window may no longer fit on the screen.

You can fix this manually by editing the config file located at `~/.var/app/com.spotify.Client/config/spotify/prefs`. Look for the keys starting with `app.window` and remove them, or set them to something reasonable.

**Comment by NeroVanbiervliet** [comment]
Thanks for the fix, works like a charm!

**Comment by gerijeb** [comment]
> I had the same issue. I think it's an upstream problem (see [here](https://community.spotify.com/t5/Desktop-Windows/Spotify-open-in-full-screen-cannot-access-taskbar-anymore/td-p/1044311)). Spotify will try to start with the same window dimensions as the last session. If your screen resolution changes (gets smaller) the window may no longer fit on the screen.
> 
> You can fix this manually by editing the config file located at `~/.var/app/com.spotify.Client/config/spotify/prefs`. Look for the keys starting with `app.window` and remove them, or set them to something reasonable.

Worked on Pop!_OS 21.04, thanks!
