### ISSUE TITLE
flatpak install fails with 404 error

### ISSUE THREAD

**Issue by tonyjames** [flathub/com.spotify.Client#7]
flatpak install --from https://s3.amazonaws.com/alexlarsson/spotify-repo/spotify.flatpakref gives the error:

error: While downloading http://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.59.395.ge6ca9946-18_amd64.deb: Server returned status 404: Not Found

Upon checking the repo the file that should be downloaded appears to be:

spotify-client_1.0.64.401.g9d720389-21_amd64.deb

**Comment by TingPing** [comment]
> flatpak install --from https://s3.amazonaws.com/alexlarsson/spotify-repo/spotify.flatpakref gives the error:

That is the old repository.

```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.spotify.Client
```

**Comment by tonyjames** [comment]
Ah, thanks TingPing.  That appears to work.  I was following the instructions from flatpak.org.

**Comment by TingPing** [comment]
Ah, yea that apps page needs to be completely redone..
