### ISSUE TITLE
icon on flathub missing until Content Blocking is off in Firefox

### ISSUE THREAD

**Issue by bam80** [flathub/com.spotify.Client#70]
I need to turn off Content Blocking in Firefox for Spotify icon shows up on Flathub.

Probably somehow related with hosting the icon on Google, but the image in this issue still rendered Ok:
![Spotify](https://lh3.googleusercontent.com/UrY7BAZ-XfXGpfkeWg0zCCeo-7ras4DCoRalC_WXXWTK9q5b0Iw7B0YQMsVxZaNB7DM=w128)

**Comment by bam80** [comment]
Seems it happens for all icons hosted on https://lh3.googleusercontent.com/

**Comment by TingPing** [comment]
Well we don't want to rehost the image. If you know of a better official URL let me know.

**Comment by Erick555** [comment]
According to https://github.com/flathub/com.elsevier.MendeleyDesktop/pull/17#issuecomment-417306288 hosting app icons is ok.
