### ISSUE TITLE
Spotify Connect finds no devices

### ISSUE THREAD

**Issue by leehambley** [flathub/com.spotify.Client#85]
I suspect this is some issue with some kind of sandboxing against network outreach, or multicast. 

I'm not familiar with the nature of flatpaks or how to debug/diagnose this, but when I run spotify outside of a flatpak it has previously worked.

I googled around to no avail trying to research a fix for this, struggled to find info on the nature of sandboxing flatpak networking, and how spotify connect really works.

OS: Fedora 30 64bit 

```
$ flatpak list | grep Spotify
Spotify	com.spotify.Client	1.1.5.153	stable	system
```

Any requests for more info to diagnose will be answered prompty, I rely completely on spotify connect as my laptop and office aren't equipped with wired speakers, only a Sonos PLAY:3

**Comment by leehambley** [comment]
With `--share network` this works better, but not all of my devices are shown... ?

**Comment by TingPing** [comment]
It already has `--share=network` (without it then it wouldn't stream at all) and locally it works for all of my devices.

I don't think there is anything further this package can do honestly.

**Comment by leehambley** [comment]
Understood. Thanks.
