### ISSUE TITLE
Installation issue in Raspbian

### ISSUE THREAD

**Issue by 10stars19** [flathub/com.spotify.Client#88]
Trying to install spotify using flatpak in Raspbian. 

I connected to the flathub repository but Spotify client is not found.

Name            Options
flathub           system
gnome-apps  system
repository       system

pi@raspberrypi:~ $ sudo flatpak install flathub com.spotify.Client
Looking for matches…
error: Nothing matches com.spotify.Client in remote flathub

**Comment by Erick555** [comment]
Is it arm? Spotify app is only for x86.

**Comment by 10stars19** [comment]
Thanks for your reply. Yes it's ARM. i have similar issue with Mendeley desktop. However, I would have expected that it was at least found in repository, but then either not able to run/ installed.

**Comment by TingPing** [comment]
Yeah they just don't make arm releases afiak.
