### ISSUE TITLE
Connection time out

### ISSUE THREAD

**Issue by rifkiaz** [flathub/com.spotify.Client#89]
hello i'm trying to install spotify in the last few times. but it's been two days the connection is always time out
![Cuplikan layar dari 2019-08-14 18-05-24](https://user-images.githubusercontent.com/23344569/63016663-7820f400-bebe-11e9-972b-d4ad1e858df9.png)

**Comment by Erick555** [comment]
https://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.1.10.546.ge08ef575-19_amd64.deb works for me.

**Comment by rifkiaz** [comment]
okay, the link is working again, before I've waited a few hours, but it's still time out, thanks for your response
