### ISSUE TITLE
Missing albums art and categories

### ISSUE THREAD

**Issue by 1LinuxGuy** [flathub/com.spotify.Client#9]
I'm submitting again, because my bug was rapidly closed, saying it was fixed, but it is not.

I tried to install, uninstall, reinstall.

I uninstalled everything that was listed in : flatpak list

Note that after every install of Spotify, it will open as if I already submitted my username and password. Which I did on first install only. So, maybe there's a config file somewhere that needs to be deleted. I don't know where flatpak/flathub Apps are stored on the system. 

Some parts of Spotify can show albums art.

![capture d ecran de 2017-10-04 14 56 38](https://user-images.githubusercontent.com/19640810/31194508-5d96fea6-a915-11e7-91fb-ea00514c63e0.png)

![capture d ecran de 2017-10-04 14 56 54](https://user-images.githubusercontent.com/19640810/31194532-6c9f3fa8-a915-11e7-90b6-b4fa478cdeaf.png)

![capture d ecran de 2017-10-04 14 57 38](https://user-images.githubusercontent.com/19640810/31194536-7460467e-a915-11e7-91a5-9a4ce43bd844.png)

![capture d ecran de 2017-10-04 14 58 12](https://user-images.githubusercontent.com/19640810/31194546-7e4bd180-a915-11e7-97c4-c60e50307a31.png)

![capture d ecran de 2017-10-04 14 57 50](https://user-images.githubusercontent.com/19640810/31194554-84de9190-a915-11e7-8f31-5850468cb0dc.png)

**Comment by TingPing** [comment]
> I'm submitting again

Don't do that. The bug was fixed it takes time to build and make it to the servers.
