### ISSUE TITLE
URI's open a new instance of Spotify each time

### ISSUE THREAD

**Issue by Bryophyllum** [flathub/com.spotify.Client#95]
I'm using Firefox 69.0.1 on Fedora Silverblue 31 (if that matters), and this is not an issue when opening links to Telegram content. Here is an example, just copy and paste it to Firefox's URL bar while Spotify is opened: `spotify:playlist:37i9dQZF1DWURCUKHUKWCX`

**Comment by Erick555** [comment]
Can confirm this behavior. I heard such issues may be elated to some xauth or iceauth permissions.

**Comment by TingPing** [comment]
Probably nothing we can do about this. Can somebody confirm it works outside the sandbox?

**Comment by Erick555** [comment]
@Bryophyllum the latter

**Comment by Bryophyllum** [comment]
I spun up a fresh Fedora Workstation 30 virtual machine in GNOME Boxes, and, as per instructions on [Fedora Docs](https://docs.fedoraproject.org/en-US/quick-docs/installing-spotify/#_using_the_rpm_fusion_repository), I installed Spotify from RPM Fusion repository via `dnf`.

The results are the same, a new instance of Spotify was opened. I'm closing this issue.

**Comment by TingPing** [comment]
I added a hack to workaround this bug: 9c21e97e8c5f2cfd1c5294b93aa7689a9ee90c3c
