### ISSUE TITLE
Password request after open (ramdomly)

### ISSUE THREAD

**Issue by fvguilherme** [flathub/com.spotify.Client#96]
The program is asking for the password from time to time. I don't know what is making it forgot the password.

**Comment by TingPing** [comment]
Can't reproduce.

**Comment by Erick555** [comment]
@fvguilherme do you use host adblocking?

**Comment by fvguilherme** [comment]
no, I don't. I have a premium account.

**Comment by TingPing** [comment]
All I can suggest is try removing your current profile (Just delete `~/.var/app/com.spotify.Client`) and hope the bug doesn't come back.

**Comment by Erick555** [comment]
I wonder if this is caused by spotify writing some state to non persistent dir in sandbox.

**Comment by TingPing** [comment]
If it is doing that, it is specific to their system.

**Comment by Erick555** [comment]
As I said it also happens for me, not randomly but always when I start spotify on fresh boot.

**Comment by TingPing** [comment]
But it has never happened a single time for me. So clearly there is an environmental influence.

**Comment by fvguilherme** [comment]
> All I can suggest is try removing your current profile (Just delete `~/.var/app/com.spotify.Client`) and hope the bug doesn't come back.

looks like this has solved the problem. Thanks.
