### ISSUE TITLE
Symbolic Icon

### ISSUE THREAD

**Issue by JasonLG1979** [flathub/com.spotify.Client#97]
I know according to https://github.com/flathub/com.spotify.Client/issues/68#issuecomment-446614294 Icon refrences are internal but would that stop you from adding a symbolic icon? All you would have to do is put a com.spotify.Client-symbolic.svg icon in /share/icons/hicolor/symbolic/apps

The biggest issue I can see is figuring out if a symbolic icon can legally be redistributed.

At the moment What I've done is created my own symbolic icon from the Spotify logo svg at wikipedia and placed it in ~/.local/share/icons/hicolor/symbolic/apps

It fits in much better than the full color icon or a desaturated full color icon.
![Screenshot from 2019-10-11 23-05-44](https://user-images.githubusercontent.com/6667703/66694692-f0682380-ec7b-11e9-889a-a89b82c866e2.png)

**Comment by JasonLG1979** [comment]
According to:
https://developer.spotify.com/branding-guidelines/

I don't think that a Spotify symbolic icon would be considered a misuse of the logo/icon anymore than how the icon that ships with the app is a misuse.

**Comment by TingPing** [comment]
I'll accept a PR adding it.

**Comment by JasonLG1979** [comment]
Yep. I have no idea how to actually add the icon to the flatpak. It also might be a good idea to add a duplicate spotify-client-symbolic.svg so there's an icon that matches what Spotify broadcasts in MPRIS or anywhere else you can't control.

And hey long time no see.

**Comment by TingPing** [comment]
I just realized your example of the icon in Fedora is a bad one because it already makes the colored icon greyscale which looks *fine*.

**Comment by JasonLG1979** [comment]
> I just realized your example of the icon in Fedora is a bad one because it already makes the colored icon greyscale which looks _fine_.

The above screenshot is the symbolic icon. The default icon is blurry (because it's a png) and looks like crap.

**Comment by JasonLG1979** [comment]
Here's what the original icon looks like:
![Screenshot from 2019-10-12 01-22-03](https://user-images.githubusercontent.com/6667703/66696144-fadfe880-ec8e-11e9-84e0-c027f1cc889d.png)

**Comment by TingPing** [comment]
For doing nothing I think its acceptable, and only Fedora adds the silly icon there anyway.

**Comment by JasonLG1979** [comment]
> For doing nothing I think its acceptable, and only Fedora adds the silly icon there anyway.

No, desaturating full color icons is default GNOME behaviour.

https://github.com/GNOME/gnome-shell/commit/1c117c469a23a0d2608abf39c86caca251bc1d5a

**Comment by JasonLG1979** [comment]
And icons in the panel next to the app's name is also default GNOME behaviour.

Some themes hide them though.

**Comment by JasonLG1979** [comment]
I just figured it would be a pretty cheap little improvement.

**Comment by JasonLG1979** [comment]
I can see why it was done but I'm not a huge fan of desaturating full color icons. Desaturating the icons can make them less "readable" especially if the icon contains colors that have about the same gray value. It also makes it look like there might be something wrong with the app, like why is the icon grayed out?

**Comment by TingPing** [comment]
Hmm, my mistake.

Anyway just copy how the appdata file is handled with the icon: https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.json#L107-L139

**Comment by TingPing** [comment]
If we give in to distributing an icon you can add the non-symbolic one also.

**Comment by JasonLG1979** [comment]
Sure. I'll find a full color svg or just make one using their color palette out of the symbolic icon. png icons are icky,lol!!!

**Comment by JasonLG1979** [comment]
> Anyway just copy how the appdata file is handled with the icon: https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.json#L107-L139

So add the icons.

Delete this line:
```
"for size in 16 22 24 32 48 64 128 256 512; do install -Dm644 share/spotify/icons/spotify-linux-$size.png export/share/icons/hicolor/${size}x${size}/apps/com.spotify.Client.png; done",
```

And add something like:

```
"install -Dm644 com.spotify.Client.svg /share/icons/hicolor/scalable/apps/com.spotify.Client.svg"
"install -Dm644 com.spotify.Client.svg /share/icons/hicolor/scalable/apps/spotify-client.svg"
"install -Dm644 com.spotify.Client.svg /share/icons/hicolor/symbolic/apps/com.spotify.Client-symbolic.svg"
"install -Dm644 com.spotify.Client.svg /share/icons/hicolor/symbolic/apps/spotify-client-symbolic.svg"
```

To the build section?

Is it /app/share/icons or just /share/icons?

**Comment by tored** [comment]
Apologies for commenting on a closed issue, this change may have broken icons for us that is not running a fancy desktop like Gnome.

Running Ubuntu MATE 20.10 and my alt-tab icon and taskbar icon does not show the Spotify icon, my start menu does however (Brisk menu Launcher)

See this related issue for the Slack flatpak

https://github.com/flathub/com.slack.Slack/issues/9

**Comment by TingPing** [comment]
@tored Open a new issue it has nothing to do with this.
